export interface LanguageFAQ {
    question: string;
    answer: string;
}

export interface LanguagePageData {
    slug: string;
    language: string;
    nativeName: string;
    speakers: string;
    regions: string;
    description: string;
    /** Unique intro paragraph for the hero section */
    intro: string;
    /** Language-specific challenges Zavi solves */
    challenges: string[];
    /** Unique use cases for this language */
    useCases: { title: string; text: string }[];
    /** Unique FAQ for this language */
    faq: LanguageFAQ[];
    /** Script/writing system type for feature descriptions */
    scriptInfo: string;
}

export const languages: LanguagePageData[] = [
    {
        slug: 'hindi',
        language: 'Hindi',
        nativeName: 'हिन्दी',
        speakers: '600+ million',
        regions: 'India, Nepal, Fiji',
        description: 'Hindi is the most widely spoken language in India and the fourth most spoken language globally.',
        intro: 'Hindi speakers often switch between Hindi and English mid-sentence — a style known as "Hinglish." Zavi AI handles this code-switching seamlessly, recognizing when you blend both languages and producing clean, contextually correct text in Devanagari or Roman script.',
        scriptInfo: 'Devanagari script with complex conjuncts and matras',
        challenges: [
            'Hinglish code-switching — mixing Hindi and English words naturally in one sentence',
            'Devanagari conjuncts and matras that are tedious to type on a mobile keyboard',
            'Formal vs. informal Hindi register (आप vs. तुम) context detection',
            'Regional dialect variations across Northern India, Rajasthan, and Bihar',
        ],
        useCases: [
            { title: 'Business emails in Shuddh Hindi', text: 'Dictate formal Hindi correspondence naturally — Zavi converts casual speech into polished, professional Hindi with correct honorifics and formal vocabulary.' },
            { title: 'WhatsApp in Hinglish', text: 'Chat the way you actually talk. Speak in your natural Hindi-English mix and Zavi transcribes it exactly, keeping the Hinglish flavor your friends expect.' },
            { title: 'Hindi content creation', text: 'Blog writers and social media creators can dictate long-form Hindi content 4x faster than typing on a Devanagari keyboard.' },
        ],
        faq: [
            { question: 'Can Zavi understand Hinglish (Hindi + English)?', answer: 'Yes. Zavi AI is trained on natural Hindi speech patterns including code-switching. It recognizes when you mix Hindi and English and transcribes both correctly.' },
            { question: 'Does Zavi support Devanagari script output?', answer: 'Absolutely. Zavi outputs Hindi text in Devanagari script with correct matras, conjuncts, and punctuation. You can also choose Romanized Hindi output.' },
            { question: 'Which Hindi dialects does Zavi support?', answer: 'Zavi supports standard Hindi (Khariboli) as well as common regional accents from across India, including influences from Bhojpuri, Rajasthani, and other regional varieties.' },
        ],
    },
    {
        slug: 'spanish',
        language: 'Spanish',
        nativeName: 'Español',
        speakers: '550+ million',
        regions: 'Spain, Latin America, USA',
        description: 'Spanish is the second most spoken language by native speakers and is used across 20+ countries.',
        intro: 'With over 20 regional varieties — from Castilian Spanish to Mexican, Argentine, and Caribbean dialects — Spanish voice typing needs to understand diverse accents and local vocabulary. Zavi AI adapts to your specific Spanish dialect and even handles Spanglish for US-based speakers.',
        scriptInfo: 'Latin alphabet with ñ, accented vowels, and inverted punctuation',
        challenges: [
            'Regional accent diversity — Mexican, Argentine, Colombian, and Castilian pronunciations differ significantly',
            'Correct placement of accent marks (á, é, í, ó, ú) and ñ that are easy to forget when typing',
            'Subjunctive mood and complex verb conjugations that speech-to-text often gets wrong',
            'Spanglish code-switching common among US Hispanic speakers',
        ],
        useCases: [
            { title: 'Cross-dialect business communication', text: 'Whether you speak Mexican Spanish or Castilian, Zavi understands your accent and produces text that reads naturally for any Spanish-speaking audience.' },
            { title: 'Spanish social media content', text: 'Create engaging Spanish-language posts and captions by speaking naturally. Zavi handles the accents, ñ, and inverted punctuation marks automatically.' },
            { title: 'Spanish ↔ English translation', text: 'Speak in Spanish, get output in English — or vice versa. Ideal for bilingual professionals working across Latin America and the US.' },
        ],
        faq: [
            { question: 'Which Spanish dialects does Zavi support?', answer: 'Zavi supports all major Spanish dialects including Mexican, Castilian, Argentine, Colombian, Caribbean, and Central American varieties. It adapts to your accent automatically.' },
            { question: 'Does Zavi add accent marks automatically?', answer: 'Yes. Zavi automatically inserts correct accent marks (tildes), ñ, and inverted punctuation (¿ ¡) so your Spanish text is grammatically correct without manual editing.' },
            { question: 'Can I use Spanglish with Zavi?', answer: 'Yes. Zavi recognizes English-Spanish code-switching and accurately transcribes both languages within the same sentence.' },
        ],
    },
    {
        slug: 'french',
        language: 'French',
        nativeName: 'Français',
        speakers: '310+ million',
        regions: 'France, Canada, Africa',
        description: 'French is an official language in 29 countries and is widely used in international diplomacy.',
        intro: 'French pronunciation is notoriously different from its spelling — silent letters, nasal vowels, and liaisons make voice-to-text especially tricky. Zavi AI is tuned for spoken French, automatically producing correctly spelled text with all accents (é, è, ê, ë, ç) and proper grammatical agreements.',
        scriptInfo: 'Latin alphabet with cedillas, accents (aigu, grave, circonflexe), and ligatures',
        challenges: [
            'Silent letters and liaisons — spoken French sounds very different from how it is written',
            'Cedillas (ç), accents (é, è, ê, ë), and special characters that slow down mobile typing',
            'Gender agreement and complex verb conjugations that are hard to get right in real-time',
            'Differences between Metropolitan French, Québécois, and African French varieties',
        ],
        useCases: [
            { title: 'International diplomacy & formal correspondence', text: 'Dictate polished, formal French for diplomatic or business communications. Zavi ensures correct vous/tu register and formal conventions.' },
            { title: 'Québécois French support', text: 'Canadian French speakers can dictate naturally — Zavi understands joual expressions and Québécois pronunciation without defaulting to Parisian French.' },
            { title: 'French academic writing', text: 'Students and researchers can dictate essays and papers in French, with Zavi handling the complex grammar, subjunctive, and literary tenses.' },
        ],
        faq: [
            { question: 'Can Zavi handle French accents and special characters?', answer: 'Yes. Zavi automatically inserts all French diacritical marks including é, è, ê, ë, à, ç, and ù, producing correctly spelled French text.' },
            { question: 'Does Zavi understand Canadian French?', answer: 'Yes. Zavi supports both Metropolitan (Parisian) French and Canadian French (Québécois), recognizing the distinct pronunciation and vocabulary differences.' },
            { question: 'How does Zavi handle French gender agreements?', answer: 'Zavi\'s AI understands French grammatical gender and ensures adjective-noun agreements are correct in the output text.' },
        ],
    },
    {
        slug: 'german',
        language: 'German',
        nativeName: 'Deutsch',
        speakers: '130+ million',
        regions: 'Germany, Austria, Switzerland',
        description: 'German is the most spoken native language in Europe and a key business language globally.',
        intro: 'German is famous for its long compound nouns and complex grammatical cases — challenges that make voice typing both more valuable and more difficult. Zavi AI correctly handles German compound word formation, noun capitalization, and case endings that other speech-to-text tools routinely get wrong.',
        scriptInfo: 'Latin alphabet with umlauts (ä, ö, ü) and Eszett (ß)',
        challenges: [
            'Compound nouns (Zusammensetzungen) that can be extremely long and need correct formation',
            'Noun capitalization rules unique to German — every noun must be capitalized',
            'Four grammatical cases (Nominativ, Akkusativ, Dativ, Genitiv) with complex declension',
            'Differences between Hochdeutsch, Austrian German, and Swiss German',
        ],
        useCases: [
            { title: 'German business communication', text: 'Dictate professional German emails and reports. Zavi handles the formal Sie/du distinction and produces Geschäftsdeutsch with correct compound nouns.' },
            { title: 'Technical & engineering documentation', text: 'German technical writers can dictate complex documentation with specialized compound terms — Zavi capitalizes nouns and forms compounds correctly.' },
            { title: 'Austrian & Swiss German support', text: 'Speak in your regional variety — Zavi understands Austrian and Swiss German accents and adapts vocabulary accordingly.' },
        ],
        faq: [
            { question: 'Does Zavi capitalize German nouns correctly?', answer: 'Yes. Zavi automatically capitalizes all German nouns in the output, following standard German orthography rules.' },
            { question: 'Can Zavi handle long German compound words?', answer: 'Yes. Zavi correctly forms German compound nouns (e.g., Rindfleischetikettierungsüberwachungsaufgabenübertragungsgesetz) from natural speech.' },
            { question: 'Does Zavi support Swiss German?', answer: 'Zavi supports standard German (Hochdeutsch) with accent adaptation for Austrian and Swiss speakers. Swiss German dialect (Schwyzerdütsch) recognition is continuously improving.' },
        ],
    },
    {
        slug: 'japanese',
        language: 'Japanese',
        nativeName: '日本語',
        speakers: '125+ million',
        regions: 'Japan',
        description: 'Japanese is spoken primarily in Japan and features three writing systems: hiragana, katakana, and kanji.',
        intro: 'Japanese text requires juggling three writing systems — hiragana, katakana, and kanji — making it one of the slowest languages to type. Zavi AI converts your spoken Japanese into properly formatted text with correct kanji selection, katakana for loanwords, and appropriate particle usage, eliminating the tedious IME conversion process.',
        scriptInfo: 'Three scripts: Hiragana, Katakana, and Kanji (Chinese characters)',
        challenges: [
            'Kanji selection — spoken words can map to multiple kanji with different meanings',
            'Three-script mixing (hiragana, katakana, kanji) that requires constant IME switching',
            'Keigo (敬語) honorific speech levels for business vs. casual contexts',
            'Particles (は, が, を, に) that are grammatically crucial but easy to misplace',
        ],
        useCases: [
            { title: 'Skip the IME entirely', text: 'Japanese typing typically requires selecting kanji from an IME dropdown. With Zavi, just speak — the AI picks the correct kanji based on context, saving enormous time.' },
            { title: 'Business Japanese (ビジネス日本語)', text: 'Dictate formal business Japanese with correct keigo. Zavi converts casual speech into professional language with appropriate honorific levels.' },
            { title: 'Mixed Japanese-English content', text: 'Tech workers and academics who mix Japanese and English can dictate naturally — Zavi outputs Japanese in kanji/kana and English terms in katakana or Roman letters as appropriate.' },
        ],
        faq: [
            { question: 'How does Zavi choose the right kanji?', answer: 'Zavi uses contextual AI to select the correct kanji based on the surrounding words and meaning, similar to how a native speaker would choose — but without the IME popup.' },
            { question: 'Does Zavi support keigo (formal Japanese)?', answer: 'Yes. Zavi can detect formal speech patterns and output appropriate keigo, including sonkeigo (respectful) and kenjōgo (humble) forms.' },
            { question: 'Can Zavi handle katakana for English loanwords?', answer: 'Yes. Zavi automatically converts English loanwords to katakana and keeps native Japanese words in hiragana/kanji.' },
        ],
    },
    {
        slug: 'korean',
        language: 'Korean',
        nativeName: '한국어',
        speakers: '80+ million',
        regions: 'South Korea, North Korea',
        description: 'Korean uses the Hangul alphabet, widely considered one of the most efficient writing systems.',
        intro: 'While Hangul is elegantly designed, typing Korean on mobile still involves combining jamo into syllable blocks — a process that\'s slower than speaking. Zavi AI converts spoken Korean into perfectly formed Hangul text with correct spacing, particles, and the formal/informal speech levels (존댓말/반말) that Korean requires.',
        scriptInfo: 'Hangul syllable blocks composed of jamo (consonant and vowel components)',
        challenges: [
            'Korean speech levels (존댓말 vs. 반말) — formal and informal registers must match the context',
            'Correct spacing between words, which Korean speakers often struggle with even when typing',
            'Sino-Korean vs. native Korean number systems used in different contexts',
            'Particles (은/는, 이/가, 을/를) that change based on the preceding syllable\'s final consonant',
        ],
        useCases: [
            { title: 'KakaoTalk messaging', text: 'Dictate Korean messages at the speed of thought. Zavi handles the 반말 register naturally for chatting with friends on KakaoTalk.' },
            { title: 'Formal Korean business writing', text: 'Switch to professional 존댓말 effortlessly. Zavi detects formal speech and outputs polished business Korean with correct honorifics.' },
            { title: 'Korean content creation', text: 'K-content creators can dictate scripts, subtitles, and social posts in Korean 4x faster than thumb-typing Hangul on mobile.' },
        ],
        faq: [
            { question: 'Does Zavi handle Korean speech levels correctly?', answer: 'Yes. Zavi distinguishes between 존댓말 (formal/polite) and 반말 (informal/casual) speech levels and maintains consistency in the output.' },
            { question: 'How does Zavi handle Korean spacing?', answer: 'Zavi automatically applies correct Korean word spacing (띄어쓰기) rules, which even native speakers find challenging.' },
            { question: 'Can Zavi transcribe Korean with English loanwords?', answer: 'Yes. Zavi handles Konglish and English loanwords, rendering them in Hangul or keeping them in English based on common Korean writing conventions.' },
        ],
    },
    {
        slug: 'mandarin-chinese',
        language: 'Mandarin Chinese',
        nativeName: '普通话',
        speakers: '920+ million',
        regions: 'China, Taiwan, Singapore',
        description: 'Mandarin Chinese is the most spoken language in the world by native speakers.',
        intro: 'Typing Chinese characters is painfully slow — each character requires a pinyin input plus selection from a list of homophones. Zavi AI eliminates this bottleneck entirely: speak naturally in Mandarin and get correctly chosen characters instantly, with the AI disambiguating homophones using context rather than requiring manual selection.',
        scriptInfo: 'Chinese characters (Simplified and Traditional) with tonal distinctions',
        challenges: [
            'Homophone disambiguation — Mandarin has thousands of characters that sound identical (e.g., 是/事/市 are all "shì")',
            'Simplified vs. Traditional character selection depending on the audience (Mainland China vs. Taiwan/Hong Kong)',
            'Four tones plus neutral tone that fundamentally change word meaning',
            'Chengyu (成语) four-character idioms and classical expressions used in formal writing',
        ],
        useCases: [
            { title: 'Skip pinyin input entirely', text: 'No more typing pinyin and picking from character lists. Speak in Mandarin and Zavi outputs the correct characters immediately, using context to resolve homophones.' },
            { title: 'Simplified & Traditional support', text: 'Choose your output format — Simplified for Mainland China or Traditional for Taiwan and Hong Kong audiences.' },
            { title: 'Chinese business correspondence', text: 'Dictate formal Chinese business emails and reports. Zavi produces polished text with appropriate formal expressions and correct measure words (量词).' },
        ],
        faq: [
            { question: 'How does Zavi handle Chinese homophones?', answer: 'Zavi uses contextual AI to disambiguate homophones. For example, it knows whether "shì" should be 是, 事, or 市 based on the surrounding sentence.' },
            { question: 'Does Zavi support both Simplified and Traditional Chinese?', answer: 'Yes. You can configure Zavi to output in Simplified Chinese (简体) or Traditional Chinese (繁體) based on your preference.' },
            { question: 'Can Zavi handle Chinese tones?', answer: 'Zavi\'s speech recognition is trained on tonal Mandarin and correctly distinguishes between the four tones to select the right characters.' },
        ],
    },
    {
        slug: 'arabic',
        language: 'Arabic',
        nativeName: 'العربية',
        speakers: '370+ million',
        regions: 'Middle East, North Africa',
        description: 'Arabic is an official language of 26 countries and the liturgical language of Islam.',
        intro: 'Arabic\'s right-to-left script, connected letter forms that change shape by position, and the significant gap between Modern Standard Arabic (MSA) and spoken dialects make it uniquely challenging for voice typing. Zavi AI bridges the dialect-to-MSA gap, converting your spoken Egyptian, Levantine, or Gulf Arabic into clean Modern Standard Arabic text — or keeping it in dialect if you prefer.',
        scriptInfo: 'Arabic abjad script, right-to-left, with contextual letter shaping',
        challenges: [
            'Dialect diversity — Egyptian, Levantine, Gulf, and Maghrebi Arabic are almost separate spoken languages',
            'MSA vs. dialect gap — most people speak dialect but write in Modern Standard Arabic',
            'Short vowels (harakat) are usually omitted in writing but affect meaning',
            'Right-to-left text with contextual letter shaping (initial, medial, final forms)',
        ],
        useCases: [
            { title: 'Dialect-to-MSA conversion', text: 'Speak in your Egyptian, Levantine, or Gulf dialect and get clean Modern Standard Arabic text — perfect for formal documents, articles, and professional communication.' },
            { title: 'Arabic content creation', text: 'Social media managers and bloggers can create Arabic content by speaking naturally in dialect while getting properly formatted MSA output.' },
            { title: 'Arabic-English bilingual workflows', text: 'Professionals working across Arabic and English can seamlessly switch between languages mid-dictation.' },
        ],
        faq: [
            { question: 'Which Arabic dialects does Zavi support?', answer: 'Zavi supports Modern Standard Arabic plus major dialects including Egyptian, Levantine (Syrian/Lebanese/Jordanian), Gulf, and Maghrebi Arabic.' },
            { question: 'Can Zavi convert dialect speech to MSA text?', answer: 'Yes. You can speak in your local dialect and Zavi will output clean Modern Standard Arabic, making it ideal for professional and formal writing.' },
            { question: 'Does Zavi handle Arabic diacritical marks?', answer: 'Zavi outputs standard Arabic text without short vowel marks (as is conventional). Full tashkeel can be added for educational or Quranic text contexts.' },
        ],
    },
    {
        slug: 'portuguese',
        language: 'Portuguese',
        nativeName: 'Português',
        speakers: '260+ million',
        regions: 'Brazil, Portugal, Mozambique',
        description: 'Portuguese is spoken across four continents and is the most spoken language in South America.',
        intro: 'Brazilian Portuguese and European Portuguese differ significantly in pronunciation, vocabulary, and even grammar — to the point where voice typing tools trained on one variety often fail on the other. Zavi AI recognizes both varieties and adapts its output accordingly, handling nasal vowels, cedilhas, and accent marks automatically.',
        scriptInfo: 'Latin alphabet with cedilha (ç), tildes (ã, õ), and accent marks',
        challenges: [
            'Brazilian vs. European Portuguese — pronunciation and vocabulary differences are substantial',
            'Nasal vowels (ã, õ) and diacritical marks that are frequently omitted when typing quickly',
            'Complex verb conjugations with personal infinitive (unique to Portuguese)',
            'Formal vs. informal address (você vs. tu) varies by region even within Brazil',
        ],
        useCases: [
            { title: 'Brazilian business communication', text: 'Dictate professional Portuguese emails and proposals in Brazilian Portuguese. Zavi handles the você register and Brazilian vocabulary naturally.' },
            { title: 'European Portuguese support', text: 'Portuguese speakers from Portugal can use Zavi without being forced into Brazilian Portuguese defaults — the AI adapts to European pronunciation and spelling.' },
            { title: 'Portuguese-Spanish bilingual content', text: 'Professionals working across Lusophone and Hispanic markets can dictate and translate between Portuguese and Spanish seamlessly.' },
        ],
        faq: [
            { question: 'Does Zavi distinguish Brazilian from European Portuguese?', answer: 'Yes. Zavi automatically detects which variety you\'re speaking and adjusts spelling, vocabulary, and grammar accordingly.' },
            { question: 'Does Zavi add Portuguese accent marks?', answer: 'Yes. All Portuguese diacritical marks (á, à, â, ã, é, ê, í, ó, ô, õ, ú, ç) are automatically applied.' },
            { question: 'Can Zavi translate Portuguese to Spanish?', answer: 'Yes. You can speak in Portuguese and get output in Spanish (or any of 100+ other languages), and vice versa.' },
        ],
    },
    {
        slug: 'russian',
        language: 'Russian',
        nativeName: 'Русский',
        speakers: '250+ million',
        regions: 'Russia, Eastern Europe, Central Asia',
        description: 'Russian is the most spoken Slavic language and is widely used across former Soviet countries.',
        intro: 'Russian\'s Cyrillic alphabet, six grammatical cases, and complex verb aspect system make it challenging to type quickly and accurately. Zavi AI handles spoken Russian with grammatically correct case endings, proper aspect choice (perfective vs. imperfective), and accurate Cyrillic output — no Cyrillic keyboard fumbling required.',
        scriptInfo: 'Cyrillic alphabet with 33 letters including ь (soft sign) and ъ (hard sign)',
        challenges: [
            'Cyrillic keyboard switching — many users struggle with Cyrillic input on non-Russian devices',
            'Six grammatical cases with complex declension patterns for nouns, adjectives, and pronouns',
            'Verb aspect (perfective/imperfective) that changes meaning and is hard to get right',
            'Stress patterns that are unpredictable and not marked in standard writing',
        ],
        useCases: [
            { title: 'Russian email without a Cyrillic keyboard', text: 'Traveling or using a non-Russian device? Just speak and Zavi outputs perfect Cyrillic text — no keyboard layout switching needed.' },
            { title: 'Russian academic and technical writing', text: 'Students and researchers can dictate papers in Russian with correct case endings and academic register.' },
            { title: 'CIS business communication', text: 'Professionals working across Russia and CIS countries can dictate in Russian and translate to/from English, Ukrainian, or Kazakh.' },
        ],
        faq: [
            { question: 'Does Zavi output in Cyrillic?', answer: 'Yes. Zavi outputs Russian in standard Cyrillic script with correct spelling and punctuation.' },
            { question: 'How does Zavi handle Russian grammatical cases?', answer: 'Zavi\'s AI understands Russian case grammar and produces text with correct noun, adjective, and pronoun declensions.' },
            { question: 'Can I use Zavi without a Cyrillic keyboard?', answer: 'Absolutely. Zavi is voice-based, so you don\'t need any specific keyboard layout. Just speak in Russian and get Cyrillic text output.' },
        ],
    },
    {
        slug: 'italian',
        language: 'Italian',
        nativeName: 'Italiano',
        speakers: '85+ million',
        regions: 'Italy, Switzerland, San Marino',
        description: 'Italian is a Romance language known for its musical quality and cultural significance.',
        intro: 'Italian\'s expressive, melodic speech patterns — complete with hand gestures replaced by vocal emphasis — translate beautifully to voice typing. Zavi AI captures the musicality of spoken Italian and produces grammatically polished text with correct accents (è, é, à, ò, ù), double consonants, and gender-number agreements.',
        scriptInfo: 'Latin alphabet with accented vowels (à, è, é, ì, ò, ù)',
        challenges: [
            'Double consonants (penne vs. pene) that change meaning but sound subtle in speech',
            'Regional pronunciation differences between Northern, Central, and Southern Italian',
            'Complex verb conjugations across numerous tenses and moods',
            'Accent marks on final vowels (perché, città, più) commonly omitted when typing',
        ],
        useCases: [
            { title: 'Italian business emails', text: 'Dictate professional Italian correspondence with correct formal register (Lei form) and polished prose. Zavi handles the formality native speakers expect.' },
            { title: 'Italian food & travel content', text: 'Restaurant owners, travel writers, and Italian culture bloggers can create authentic Italian content by simply speaking.' },
            { title: 'Italian-English bilingual workflows', text: 'Fashion, design, and automotive professionals who work between Italian and English can switch languages mid-dictation.' },
        ],
        faq: [
            { question: 'Does Zavi handle Italian double consonants?', answer: 'Yes. Zavi correctly distinguishes words with double consonants from their single-consonant counterparts based on pronunciation context.' },
            { question: 'Which Italian accents does Zavi support?', answer: 'Zavi supports standard Italian pronunciation and adapts to Northern, Central, and Southern Italian regional accents.' },
            { question: 'Does Zavi add Italian accent marks?', answer: 'Yes. Accent marks on words like perché, città, and più are automatically added.' },
        ],
    },
    {
        slug: 'dutch',
        language: 'Dutch',
        nativeName: 'Nederlands',
        speakers: '30+ million',
        regions: 'Netherlands, Belgium, Suriname',
        description: 'Dutch is spoken in the Netherlands and Belgium, and is closely related to English and German.',
        intro: 'Dutch sits between English and German but has its own distinct pronunciation rules, compound word formation, and the notoriously tricky "de/het" article system. Zavi AI handles Dutch compound words, correct article assignment, and the guttural sounds that other voice tools often misinterpret.',
        scriptInfo: 'Latin alphabet with digraphs (ij, oe, ui, ei) and diacritical marks',
        challenges: [
            'De/het article assignment — even native speakers disagree on some words',
            'Compound word formation similar to German but with different spelling rules',
            'Guttural "g" and "ch" sounds that non-Dutch speech models often misrecognize',
            'Differences between Netherlands Dutch (ABN) and Belgian Dutch (Flemish)',
        ],
        useCases: [
            { title: 'Dutch business correspondence', text: 'Dictate professional Dutch emails with correct de/het articles and formal u/jij register. Zavi produces polished ABN text.' },
            { title: 'Flemish Dutch support', text: 'Belgian Dutch speakers can use Zavi without the AI defaulting to Netherlands Dutch — Flemish vocabulary and pronunciation are supported.' },
            { title: 'Dutch-English translation', text: 'The Netherlands\' bilingual business culture means frequent switching. Dictate in Dutch, output in English — or mix both.' },
        ],
        faq: [
            { question: 'Does Zavi handle de/het articles?', answer: 'Yes. Zavi uses contextual AI to assign the correct Dutch article (de or het) to nouns.' },
            { question: 'Does Zavi support Flemish (Belgian Dutch)?', answer: 'Yes. Zavi supports both Netherlands Dutch and Belgian Dutch (Flemish), adapting to vocabulary and pronunciation differences.' },
            { question: 'Can Zavi handle Dutch compound words?', answer: 'Yes. Dutch compounds are correctly formed as single words following standard Dutch spelling rules.' },
        ],
    },
    {
        slug: 'turkish',
        language: 'Turkish',
        nativeName: 'Türkçe',
        speakers: '85+ million',
        regions: 'Turkey, Cyprus, Central Asia',
        description: 'Turkish is an agglutinative language spoken across Turkey and parts of Central Asia.',
        intro: 'Turkish agglutination means a single word can carry the meaning of an entire English sentence — making accurate voice typing incredibly valuable. Zavi AI correctly handles Turkish suffix chains, vowel harmony, and the special characters (ç, ğ, ı, ö, ş, ü) that standard keyboards make difficult to type.',
        scriptInfo: 'Latin alphabet with special characters: ç, ğ, ı (dotless i), ö, ş, ü',
        challenges: [
            'Agglutinative morphology — long suffix chains must follow strict vowel harmony rules',
            'Dotted İ vs. dotless I distinction (unique to Turkish) that software often gets wrong',
            'Special characters (ç, ğ, ş, ö, ü) that slow down typing on non-Turkish keyboards',
            'Vowel harmony (front/back, rounded/unrounded) that governs suffix selection',
        ],
        useCases: [
            { title: 'Turkish professional communication', text: 'Dictate business Turkish with correct suffix formations. Zavi ensures vowel harmony and correct agglutination in formal writing.' },
            { title: 'Turkish social media', text: 'Create Turkish content quickly — speaking is far faster than typing with special characters, especially on mobile.' },
            { title: 'Turkish-English business workflows', text: 'Turkey\'s international business community frequently switches between Turkish and English. Zavi handles both seamlessly.' },
        ],
        faq: [
            { question: 'Does Zavi handle Turkish special characters?', answer: 'Yes. All Turkish-specific characters (ç, ğ, ı, İ, ö, ş, ü) are automatically included in the output.' },
            { question: 'How does Zavi handle Turkish agglutination?', answer: 'Zavi correctly forms Turkish agglutinated words with proper vowel harmony, producing natural-sounding suffix chains.' },
            { question: 'Does Zavi distinguish dotted and dotless I?', answer: 'Yes. Zavi correctly handles the İ/I and i/ı distinction that is unique to Turkish.' },
        ],
    },
    {
        slug: 'polish',
        language: 'Polish',
        nativeName: 'Polski',
        speakers: '45+ million',
        regions: 'Poland, diaspora worldwide',
        description: 'Polish is a West Slavic language and one of the official languages of the European Union.',
        intro: 'Polish pronunciation with its consonant clusters (like "szcz" or "prz") and seven grammatical cases makes voice typing both incredibly useful and technically demanding. Zavi AI accurately decodes Polish speech — including the notoriously difficult sibilants — and produces text with correct declensions and all special characters (ą, ć, ę, ł, ń, ó, ś, ź, ż).',
        scriptInfo: 'Latin alphabet with 9 additional characters: ą, ć, ę, ł, ń, ó, ś, ź, ż',
        challenges: [
            'Complex consonant clusters (szcz, prz, chrz) that challenge speech recognition',
            'Seven grammatical cases with extensive noun and adjective declension',
            'Nine special characters (ą, ć, ę, ł, ń, ó, ś, ź, ż) tedious to type on non-Polish keyboards',
            'Verb aspect and motion verbs with numerous prefixed variants',
        ],
        useCases: [
            { title: 'Polish diaspora communication', text: 'Polish speakers living abroad often lack a Polish keyboard. Speak in Polish and Zavi outputs perfect text with all special characters — no keyboard configuration needed.' },
            { title: 'Polish business writing', text: 'Dictate professional Polish correspondence with correct case endings and formal Pan/Pani address forms.' },
            { title: 'Polish-English translation', text: 'Poland\'s growing tech industry means constant Polish-English switching. Dictate in Polish, get English output for international colleagues.' },
        ],
        faq: [
            { question: 'Does Zavi handle Polish special characters?', answer: 'Yes. All nine Polish diacritical characters (ą, ć, ę, ł, ń, ó, ś, ź, ż) are automatically included.' },
            { question: 'Can Zavi handle Polish consonant clusters?', answer: 'Yes. Zavi\'s speech recognition is trained on Polish phonology and accurately decodes complex clusters like szcz, prz, and chrz.' },
            { question: 'How does Zavi handle Polish grammatical cases?', answer: 'Zavi produces text with correct case declensions for nouns, adjectives, and pronouns across all seven Polish cases.' },
        ],
    },
    {
        slug: 'swedish',
        language: 'Swedish',
        nativeName: 'Svenska',
        speakers: '13+ million',
        regions: 'Sweden, Finland',
        description: 'Swedish is a North Germanic language closely related to Norwegian and Danish.',
        intro: 'Swedish\'s tonal word accent system (Accent 1 vs. Accent 2) gives words different meanings based on pitch — a subtlety most voice tools miss. Zavi AI is trained on Swedish prosody and correctly disambiguates tonal pairs, handles the å/ä/ö characters, and produces text with correct en/ett article usage.',
        scriptInfo: 'Latin alphabet with three additional vowels: å, ä, ö',
        challenges: [
            'Tonal word accents (Accent 1 vs. 2) that distinguish word meanings (anden = "the duck" vs. "the spirit")',
            'En/ett gender system that determines article and adjective forms',
            'Three extra vowels (å, ä, ö) not available on standard international keyboards',
            'Compound word formation following Swedish spelling conventions',
        ],
        useCases: [
            { title: 'Swedish workplace communication', text: 'Dictate Swedish emails and Slack messages. Zavi handles the informal du-reforms style common in Swedish workplaces while maintaining professional clarity.' },
            { title: 'Swedish-English tech workflows', text: 'Sweden\'s tech industry operates bilingually. Switch between Swedish and English mid-conversation and Zavi follows along.' },
            { title: 'Finland-Swedish support', text: 'Swedish speakers in Finland can use Zavi with their natural accent and vocabulary — it\'s not locked to Rikssvenska.' },
        ],
        faq: [
            { question: 'Does Zavi handle Swedish tonal accents?', answer: 'Yes. Zavi\'s speech model recognizes Swedish pitch accent patterns to correctly disambiguate words that differ only by tone.' },
            { question: 'Does Zavi support å, ä, ö?', answer: 'Yes. All three Swedish-specific vowels are automatically included in the output text.' },
            { question: 'Can Zavi handle Swedish compound words?', answer: 'Yes. Swedish compounds are correctly formed as single words (e.g., sjukhus, flygplats) following standard Swedish rules.' },
        ],
    },
    {
        slug: 'thai',
        language: 'Thai',
        nativeName: 'ภาษาไทย',
        speakers: '60+ million',
        regions: 'Thailand',
        description: 'Thai is a tonal language with its own unique script, spoken primarily in Thailand.',
        intro: 'Thai has no spaces between words, five tones that change word meaning, and a complex script with 44 consonants and 32 vowel forms — making it one of the hardest languages to type on mobile. Zavi AI converts spoken Thai into properly segmented, correctly toned text with appropriate Thai script, eliminating the painfully slow process of selecting Thai characters.',
        scriptInfo: 'Thai script with 44 consonants, 15 vowel symbols (32 forms), no word spacing',
        challenges: [
            'No spaces between words — Thai writing runs words together, making segmentation crucial',
            'Five tones that completely change word meaning (e.g., มา "come" vs. ม้า "horse")',
            'Complex Thai script with consonant classes that determine tone rules',
            'Formal vs. informal registers and royal vocabulary (ราชาศัพท์)',
        ],
        useCases: [
            { title: 'Thai messaging without the keyboard struggle', text: 'Thai mobile typing is extremely slow due to the complex script. Speak naturally and Zavi outputs correctly segmented Thai text instantly.' },
            { title: 'Thai business communication', text: 'Dictate formal Thai business documents with correct ครับ/ค่ะ polite particles and formal register vocabulary.' },
            { title: 'Thai-English bilingual content', text: 'Thailand\'s international business community frequently mixes Thai and English. Zavi handles both scripts in the same document.' },
        ],
        faq: [
            { question: 'How does Zavi handle Thai word segmentation?', answer: 'Zavi\'s AI correctly segments Thai text even though Thai writing doesn\'t use spaces between words, using contextual understanding.' },
            { question: 'Does Zavi handle Thai tones?', answer: 'Yes. Zavi distinguishes between Thai\'s five tones to select the correct words and characters.' },
            { question: 'Does Zavi support formal Thai?', answer: 'Yes. Zavi can output formal Thai register including polite particles and appropriate vocabulary for professional contexts.' },
        ],
    },
    {
        slug: 'vietnamese',
        language: 'Vietnamese',
        nativeName: 'Tiếng Việt',
        speakers: '85+ million',
        regions: 'Vietnam, diaspora',
        description: 'Vietnamese is a tonal language that uses the Latin alphabet with additional diacritics.',
        intro: 'Vietnamese uses the Latin alphabet — but with a staggering number of diacritical marks (ă, â, đ, ê, ô, ơ, ư plus five tone marks per vowel). Typing all these accents manually is tedious. Zavi AI converts your spoken Vietnamese into fully accented text instantly, correctly handling all six tones and regional pronunciation differences between Northern, Central, and Southern Vietnamese.',
        scriptInfo: 'Latin alphabet (Quốc ngữ) with extensive diacritical marks and tone markers',
        challenges: [
            'Extensive diacritical marks — each vowel can carry one of five tone marks plus base diacritics',
            'Six tones that fundamentally change word meaning, varying by region',
            'Northern vs. Central vs. Southern Vietnamese pronunciation differences',
            'Telex/VNI input methods that require memorizing special key combinations',
        ],
        useCases: [
            { title: 'Skip Telex/VNI typing altogether', text: 'Vietnamese diacritics require special input methods (Telex, VNI). Zavi eliminates this entirely — just speak and get fully accented Vietnamese text.' },
            { title: 'Vietnamese business and government documents', text: 'Dictate formal Vietnamese with correct diacritical marks for official and professional documents.' },
            { title: 'Overseas Vietnamese communication', text: 'Vietnamese diaspora often lack Vietnamese keyboard setups. Speak in Vietnamese on any device and get perfectly accented text.' },
        ],
        faq: [
            { question: 'Does Zavi add all Vietnamese diacritical marks?', answer: 'Yes. Zavi automatically adds both base diacritics (ă, â, đ, ê, ô, ơ, ư) and all five tone marks, producing fully accented Vietnamese text.' },
            { question: 'Which Vietnamese dialect does Zavi support?', answer: 'Zavi supports Northern (Hanoi), Central (Huế), and Southern (Ho Chi Minh City) Vietnamese pronunciation.' },
            { question: 'Do I need a special Vietnamese keyboard?', answer: 'No. Zavi is entirely voice-based, so you don\'t need Telex, VNI, or any Vietnamese input method. Just speak.' },
        ],
    },
    {
        slug: 'indonesian',
        language: 'Indonesian',
        nativeName: 'Bahasa Indonesia',
        speakers: '200+ million',
        regions: 'Indonesia',
        description: 'Indonesian is the official language of Indonesia, the fourth most populous country in the world.',
        intro: 'Indonesian (Bahasa Indonesia) uses the Latin alphabet with no tones or complex script — making it one of the more accessible languages. However, its rich affixation system (prefixes, suffixes, and circumfixes) and the distinction between formal Indonesian and colloquial Jakarta Indonesian (Bahasa gaul) create unique voice typing challenges that Zavi AI handles effortlessly.',
        scriptInfo: 'Latin alphabet with straightforward spelling (largely phonetic)',
        challenges: [
            'Rich affixation system — prefixes (me-, ber-, di-), suffixes (-kan, -an), and circumfixes change word meaning',
            'Formal Bahasa Indonesia vs. informal Bahasa gaul (colloquial Jakarta Indonesian)',
            'Reduplication (e.g., anak-anak) that must be correctly hyphenated',
            'Loanwords from Dutch, Arabic, Sanskrit, and English that follow different pronunciation patterns',
        ],
        useCases: [
            { title: 'Indonesian business communication', text: 'Dictate formal Indonesian for professional communication. Zavi uses correct affixation and formal register automatically.' },
            { title: 'Indonesian social media', text: 'Create content in casual Indonesian (Bahasa gaul) for younger audiences. Zavi understands colloquial expressions and slang.' },
            { title: 'Indonesian-English bilingual workflows', text: 'Indonesia\'s startup and tech scene is increasingly bilingual. Switch between Indonesian and English seamlessly.' },
        ],
        faq: [
            { question: 'Does Zavi handle Indonesian affixation correctly?', answer: 'Yes. Zavi correctly applies Indonesian prefixes, suffixes, and circumfixes (me-...-kan, ber-...-an, etc.) in the output.' },
            { question: 'Can Zavi understand informal Indonesian?', answer: 'Yes. Zavi recognizes colloquial Jakarta Indonesian (Bahasa gaul) and can either preserve it or convert to formal Bahasa Indonesia.' },
            { question: 'Does Zavi support Indonesian reduplication?', answer: 'Yes. Reduplicated words (e.g., anak-anak, hati-hati) are correctly hyphenated in the output.' },
        ],
    },
    {
        slug: 'tamil',
        language: 'Tamil',
        nativeName: 'தமிழ்',
        speakers: '80+ million',
        regions: 'India, Sri Lanka, Singapore',
        description: 'Tamil is one of the oldest living languages in the world, with over 2,000 years of literary tradition.',
        intro: 'Tamil\'s unique script with 12 vowels, 18 consonants, and 216 combined characters makes mobile typing extremely slow. Zavi AI lets Tamil speakers bypass the complex keyboard entirely — speak in Tamil and get beautifully formatted Tamil script output with correct spelling and grammar, whether you\'re using formal literary Tamil or everyday spoken Tamil.',
        scriptInfo: 'Tamil script with 12 vowels, 18 consonants, 216 combined characters, and the unique ஃ (āytam)',
        challenges: [
            'Tamil script complexity — 247 characters including vowel-consonant combinations',
            'Significant difference between spoken Tamil (பேச்சுத் தமிழ்) and literary Tamil (செந்தமிழ்)',
            'Regional variations between India Tamil, Sri Lankan Tamil, and Singapore Tamil',
            'Transliteration inconsistencies when converting between Tamil and Latin scripts',
        ],
        useCases: [
            { title: 'Tamil content without keyboard struggle', text: 'Skip the complex Tamil keyboard layout. Speak naturally in Tamil and Zavi outputs perfectly formed Tamil script with correct conjuncts.' },
            { title: 'Formal Tamil writing', text: 'Create literary Tamil content for journalism, academic, or government use. Zavi converts spoken Tamil into polished written form.' },
            { title: 'Tamil diaspora communication', text: 'Tamil speakers in Singapore, Malaysia, and worldwide can dictate in Tamil without needing a Tamil keyboard installed.' },
        ],
        faq: [
            { question: 'Does Zavi output in Tamil script?', answer: 'Yes. Zavi outputs in proper Tamil script (தமிழ் எழுத்து) with correct vowel-consonant combinations and conjuncts.' },
            { question: 'Can Zavi handle spoken vs. literary Tamil?', answer: 'Yes. Zavi understands both colloquial spoken Tamil and can convert it to formal literary Tamil when needed.' },
            { question: 'Does Zavi support Sri Lankan Tamil?', answer: 'Yes. Zavi supports Tamil as spoken in India, Sri Lanka, and Singapore, including regional vocabulary differences.' },
        ],
    },
    {
        slug: 'bengali',
        language: 'Bengali',
        nativeName: 'বাংলা',
        speakers: '270+ million',
        regions: 'Bangladesh, India (West Bengal)',
        description: 'Bengali is the seventh most spoken language in the world and the national language of Bangladesh.',
        intro: 'Bengali\'s elegant but complex script — with conjunct consonants (যুক্তবর্ণ) that combine multiple characters into single forms — is notoriously slow to type on mobile. Zavi AI converts spoken Bengali into perfectly formed Bengali script, handling the differences between Bangladeshi Bengali and Indian Bengali (West Bengal) vocabulary and pronunciation.',
        scriptInfo: 'Bengali-Assamese script with extensive conjunct consonants (যুক্তবর্ণ)',
        challenges: [
            'Conjunct consonants (যুক্তবর্ণ) — combined character forms that are complex to type',
            'Bangladeshi vs. Indian Bengali differences in vocabulary and pronunciation',
            'Vowel inherency — the inherent /ɔ/ vowel that is not written but affects pronunciation',
            'Chandra-bindu (চন্দ্রবিন্দু) and other diacritical marks used for nasalization',
        ],
        useCases: [
            { title: 'Bengali messaging on mobile', text: 'Bengali script is among the slowest to type on smartphones. Speak instead and Zavi produces perfect Bengali text with correct conjuncts faster than any keyboard.' },
            { title: 'Bangladeshi professional documents', text: 'Create formal Bengali documents for Bangladeshi government, education, or business contexts with correct Bangladeshi Bengali conventions.' },
            { title: 'Bengali literary content', text: 'Writers and poets can dictate Bengali prose and verse with Zavi preserving the literary quality and correct orthography.' },
        ],
        faq: [
            { question: 'Does Zavi handle Bengali conjunct consonants?', answer: 'Yes. Zavi correctly forms all Bengali conjunct consonants (যুক্তবর্ণ) in the output, including complex multi-character combinations.' },
            { question: 'Does Zavi support Bangladeshi Bengali?', answer: 'Yes. Zavi supports both Bangladeshi Bengali and Indian (West Bengal) Bengali, including vocabulary and pronunciation differences.' },
            { question: 'Can Zavi handle the inherent vowel in Bengali?', answer: 'Yes. Zavi understands Bengali phonology including the inherent /ɔ/ vowel and produces correctly spelled text.' },
        ],
    },
    {
        slug: 'telugu',
        language: 'Telugu',
        nativeName: 'తెలుగు',
        speakers: '90+ million',
        regions: 'India (Andhra Pradesh, Telangana)',
        description: 'Telugu is a Dravidian language and one of the most spoken languages in India.',
        intro: 'Known as the "Italian of the East" for its vowel-ending words, Telugu has a beautiful but complex script with over 300 character combinations. Zavi AI turns spoken Telugu into perfectly rendered script — handling the distinct dialects of Andhra Pradesh and Telangana while saving you from the tedious process of typing Telugu characters on mobile.',
        scriptInfo: 'Telugu script with 60 symbols and 300+ vowel-consonant combinations',
        challenges: [
            'Over 300 vowel-consonant character combinations to navigate when typing',
            'Andhra Pradesh vs. Telangana dialect differences in pronunciation and vocabulary',
            'Formal (గ్రాంథిక) vs. colloquial (వ్యావహారిక) Telugu distinction',
            'Consonant clusters and aspirated sounds that vary by dialect',
        ],
        useCases: [
            { title: 'Telugu content creation', text: 'Tollywood and Telugu media creators can dictate scripts, articles, and social posts in Telugu 4x faster than typing the complex script.' },
            { title: 'Telugu government & education documents', text: 'Create official Telugu documents with correct formal (గ్రాంథిక) Telugu. Zavi handles the literary register automatically.' },
            { title: 'Telugu IT professional communication', text: 'Hyderabad\'s tech workforce can dictate in Telugu for personal communication while switching to English for work — all in one flow.' },
        ],
        faq: [
            { question: 'Does Zavi output in Telugu script?', answer: 'Yes. Zavi produces properly formed Telugu script (తెలుగు లిపి) with correct vowel-consonant combinations and conjuncts.' },
            { question: 'Does Zavi support Telangana Telugu?', answer: 'Yes. Zavi supports both Andhra Pradesh and Telangana varieties of Telugu, adapting to regional pronunciation and vocabulary.' },
            { question: 'Can Zavi convert spoken to formal Telugu?', answer: 'Yes. Zavi can convert colloquial spoken Telugu into formal written (గ్రాంథిక) Telugu for official documents.' },
        ],
    },
    {
        slug: 'marathi',
        language: 'Marathi',
        nativeName: 'मराठी',
        speakers: '95+ million',
        regions: 'India (Maharashtra)',
        description: 'Marathi is an Indo-Aryan language and the official language of Maharashtra, India.',
        intro: 'Marathi shares Devanagari script with Hindi but has its own unique character (ळ), distinct grammar, and different vocabulary. Zavi AI understands Marathi-specific speech patterns, including the characteristic Marathi intonation and Mumbai\'s Marathi-Hindi-English trilingual mixing, producing clean Marathi text with correct grammar and script.',
        scriptInfo: 'Devanagari script with the unique ळ (La) character specific to Marathi',
        challenges: [
            'Marathi-specific Devanagari characters (ळ) not shared with Hindi',
            'Three grammatical genders (masculine, feminine, neuter) unlike Hindi\'s two',
            'Mumbai\'s trilingual mixing of Marathi, Hindi, and English in everyday speech',
            'Seven verb conjugation patterns unique to Marathi',
        ],
        useCases: [
            { title: 'Marathi government and official documents', text: 'Maharashtra\'s official language requirement means Marathi documents are essential. Dictate formal Marathi for government, legal, and educational contexts.' },
            { title: 'Mumbai trilingual messaging', text: 'Mumbaikars naturally mix Marathi, Hindi, and English. Zavi understands this trilingual switching and transcribes it accurately.' },
            { title: 'Marathi media and content', text: 'Marathi entertainment, news, and social media content creators can produce content by speaking naturally in Marathi.' },
        ],
        faq: [
            { question: 'How is Marathi different from Hindi in Zavi?', answer: 'Zavi has a separate Marathi model that understands Marathi-specific grammar (3 genders vs. Hindi\'s 2), vocabulary, and the unique ळ character.' },
            { question: 'Does Zavi support Mumbai Marathi?', answer: 'Yes. Zavi understands the Mumbai dialect of Marathi including common Marathi-Hindi-English code-switching.' },
            { question: 'Can Zavi handle formal Marathi?', answer: 'Yes. Zavi can produce formal शुद्ध (pure) Marathi for official and literary purposes.' },
        ],
    },
    {
        slug: 'urdu',
        language: 'Urdu',
        nativeName: 'اردو',
        speakers: '230+ million',
        regions: 'Pakistan, India',
        description: 'Urdu is the national language of Pakistan and one of the 22 scheduled languages of India.',
        intro: 'Urdu\'s Nastaliq script — flowing, calligraphic, and right-to-left — is beautiful but extremely difficult to type digitally. Most Urdu speakers resort to Roman Urdu on messaging apps because Nastaliq keyboards are so cumbersome. Zavi AI changes this: speak in Urdu and get properly formatted Nastaliq script text, bringing the elegance of written Urdu back to digital communication.',
        scriptInfo: 'Nastaliq variant of Arabic script, right-to-left, with Urdu-specific characters',
        challenges: [
            'Nastaliq script is extremely difficult to type on mobile — most people use Roman Urdu instead',
            'Urdu-Hindi mutual intelligibility in speech but completely different scripts',
            'Right-to-left text with Urdu-specific characters (ٹ, ڈ, ڑ, ے) not in Arabic',
            'Formal Urdu (with Persian/Arabic loanwords) vs. everyday spoken Urdu register',
        ],
        useCases: [
            { title: 'Proper Nastaliq Urdu messaging', text: 'Stop sending Roman Urdu. Speak naturally and Zavi outputs beautiful Nastaliq script — bringing proper Urdu back to WhatsApp and social media.' },
            { title: 'Urdu literary and poetic content', text: 'Poets and writers can dictate Urdu prose, nazm, and ghazal with Zavi preserving the literary vocabulary and Nastaliq elegance.' },
            { title: 'Pakistan professional communication', text: 'Create formal Urdu documents for Pakistani government, education, and business contexts with correct Nastaliq formatting.' },
        ],
        faq: [
            { question: 'Does Zavi output in Nastaliq script?', answer: 'Yes. Zavi outputs in proper Urdu Nastaliq script, not Naskh or Roman Urdu, with all Urdu-specific characters correctly formed.' },
            { question: 'Can I switch between Urdu and Hindi?', answer: 'Yes. Despite sharing spoken intelligibility, Zavi correctly outputs in the script you choose — Nastaliq for Urdu or Devanagari for Hindi.' },
            { question: 'Does Zavi understand Pakistani Urdu vs. Indian Urdu?', answer: 'Yes. Zavi supports both Pakistani and Indian varieties of Urdu, adapting to vocabulary and pronunciation differences.' },
        ],
    },
    {
        slug: 'malay',
        language: 'Malay',
        nativeName: 'Bahasa Melayu',
        speakers: '290+ million',
        regions: 'Malaysia, Indonesia, Brunei',
        description: 'Malay is the basis of Indonesian and Malaysian languages, spoken in Southeast Asia.',
        intro: 'Malay and Indonesian are closely related but have distinct vocabularies, spelling conventions, and formal registers. Zavi AI distinguishes between Malaysian Malay (Bahasa Melayu), Indonesian (Bahasa Indonesia), and Bruneian Malay, producing text that matches the specific standard your audience expects — whether it\'s a Malaysian kerajaan document or a casual Malaysian chat.',
        scriptInfo: 'Latin alphabet (Rumi) with phonetic spelling; Jawi (Arabic-based) script also used',
        challenges: [
            'Malaysian Malay vs. Indonesian differences in vocabulary and spelling conventions',
            'Affixation system similar to Indonesian but with different prefix preferences',
            'Code-switching with English (Manglish) common in Malaysian speech',
            'Jawi (Arabic-based) script still used in religious and royal contexts',
        ],
        useCases: [
            { title: 'Malaysian government documents', text: 'Create formal Bahasa Melayu documents following Malaysian government language standards (Dewan Bahasa dan Pustaka conventions).' },
            { title: 'Malaysian casual communication', text: 'Speak in your natural Malaysian style — including Manglish mixing — and Zavi transcribes it accurately for WhatsApp and social media.' },
            { title: 'Cross-ASEAN communication', text: 'Professionals working across Malaysia, Indonesia, and Brunei can dictate in their local Malay variety and translate between standards.' },
        ],
        faq: [
            { question: 'Does Zavi distinguish Malay from Indonesian?', answer: 'Yes. Zavi recognizes Malaysian Malay and Indonesian as distinct varieties, using the correct vocabulary and spelling conventions for each.' },
            { question: 'Can Zavi handle Manglish (Malay-English mixing)?', answer: 'Yes. Zavi understands English-Malay code-switching common in Malaysian speech and transcribes both languages correctly.' },
            { question: 'Does Zavi support Jawi script?', answer: 'Currently Zavi outputs in Rumi (Latin) script. Jawi script support is on our roadmap.' },
        ],
    },
    {
        slug: 'swahili',
        language: 'Swahili',
        nativeName: 'Kiswahili',
        speakers: '100+ million',
        regions: 'East Africa (Kenya, Tanzania, Uganda)',
        description: 'Swahili is the most widely spoken African language and a lingua franca across East Africa.',
        intro: 'Swahili is Africa\'s most international language, serving as a lingua franca across East Africa. Its noun class system (with 18 classes!) and agglutinative verb structure create complex word forms that take time to type. Zavi AI handles Swahili\'s rich morphology — including the regional differences between Kenyan, Tanzanian, and Congolese Swahili — producing clean, grammatically correct text.',
        scriptInfo: 'Latin alphabet with straightforward phonetic spelling',
        challenges: [
            '18 noun classes that govern agreement patterns across verbs, adjectives, and pronouns',
            'Agglutinative verb morphology with subject, tense, object, and extension markers',
            'Regional vocabulary differences between Kenyan, Tanzanian, and Congolese Swahili',
            'Code-switching with English (in Kenya) or French (in DRC) in everyday speech',
        ],
        useCases: [
            { title: 'East African business communication', text: 'Create professional Swahili content for Kenyan, Tanzanian, or pan-East African business audiences. Zavi handles the formal register correctly.' },
            { title: 'Swahili media and journalism', text: 'Journalists and content creators can dictate Swahili articles and scripts rapidly, with Zavi ensuring correct noun class agreements.' },
            { title: 'Swahili-English bilingual workflows', text: 'East African professionals commonly switch between Swahili and English. Zavi handles this code-switching naturally.' },
        ],
        faq: [
            { question: 'Which Swahili dialect does Zavi support?', answer: 'Zavi supports standard Swahili (Kiswahili sanifu) and adapts to Kenyan, Tanzanian, and Congolese varieties.' },
            { question: 'Does Zavi handle Swahili noun classes?', answer: 'Yes. Zavi correctly handles Swahili\'s noun class agreement system, producing grammatically correct text across all 18 classes.' },
            { question: 'Can Zavi handle Sheng (Kenyan Swahili-English slang)?', answer: 'Zavi recognizes standard Swahili and common English code-switching. Support for Sheng and other urban varieties is continuously improving.' },
        ],
    },
];

export function getLanguage(slug: string): LanguagePageData | undefined {
    return languages.find((l) => l.slug === slug);
}

export function getAllLanguageSlugs(): string[] {
    return languages.map((l) => l.slug);
}
