export interface UseCase {
    slug: string;
    title: string;
    metaTitle: string;
    metaDescription: string;
    heroTitle: string;
    heroSubtitle: string;
    icon: string;
    problem: string;
    solution: string;
    howItWorks: string[];
    benefits: { title: string; description: string }[];
    exampleBefore: string;
    exampleAfter: string;
    targetAudience: string[];
    faqItems: { question: string; answer: string }[];
    relatedUseCases: string[];
}

export const useCases: UseCase[] = [
    {
        slug: 'email',
        title: 'Voice Typing for Email',
        metaTitle: 'Voice Typing for Email — Draft Emails 4x Faster with Zavi AI',
        metaDescription: 'Use Zavi AI to draft professional emails by voice. Speak naturally and get polished, grammar-perfect emails in Gmail, Outlook, and every email app. Free download.',
        heroTitle: 'Draft Professional Emails by Voice',
        heroSubtitle: 'Speak naturally. Zavi removes filler words, fixes grammar, and delivers ready-to-send emails in seconds.',
        icon: '✉️',
        problem: 'The average professional sends 40+ emails per day and spends 2.5 hours writing them. Typing on mobile is slow (38 WPM), and even desktop typing (40 WPM) can\'t keep up with the pace of modern communication. The result: rushed, error-filled emails or a growing inbox of unread messages.',
        solution: 'Zavi AI lets you dictate emails at 150 WPM — 4x faster than typing. With the Pro "Magic Wand" feature, you can even say "make this more professional" or "rewrite as bullet points" to instantly transform a rough draft into an executive-ready message.',
        howItWorks: [
            'Open Gmail, Outlook, or any email app and tap the Zavi mic (or hold action button).',
            'Speak your email naturally — include any "umms" or pauses.',
            'Need an edit? Tap the Magic Wand and say "make this sound friendlier".',
            'Need to send it hands-free? Use the Voice Agent: "Send David an email about Thursday\'s meeting".',
        ],
        benefits: [
            { title: 'Magic Wand Editing (Pro)', description: 'Transform any text just by describing the changes. Say "shorten this" or "fix grammar", and the Gemini LLM rewrites the field.' },
            { title: 'Tone Selection', description: 'Cycle through 4 tones instantly (Professional, Casual, Chat, Witty) by tapping the tone icon before you dictate.' },
            { title: 'Zero Hand Strain', description: 'The advanced Voice Agent routes multi-turn commands through your connected Gmail via OAuth—no typing needed.' },
            { title: 'Dictionary Personalization', description: 'Add your custom coworker names like "Daenerys" or "Siobhan" so the AI never mishears them.' },
        ],
        exampleBefore: 'Um, hey John, so I was thinking, uh, we should probably like meet up next Tuesday, you know, to go over the Q3 numbers.',
        exampleAfter: 'Hi John, I\'d like to schedule a meeting next Tuesday to review the Q3 numbers. Does that work for you?',
        targetAudience: ['Account Executives', 'CEOs', 'Remote workers', 'Customer support teams', 'Anyone who writes 10+ emails/day'],
        faqItems: [
            { question: 'Does Zavi work in Gmail?', answer: 'Yes. Zavi works as a system-wide keyboard, so it works perfectly across Gmail, Outlook, Apple Mail, and Yahoo Mail.' },
            { question: 'What does the Voice Agent do?', answer: 'With Zavi Pro, you can tap the paperplane icon and say "Send David an email...". The Voice Agent executes a multi-turn tool-calling loop through your connected Gmail account to send the message for you.' },
            { question: 'Can I dictate long emails?', answer: 'Yes! Zavi bypasses standard 5-minute transcription constraints via Stream Rotation, allowing seamless and infinite dictation sessions.' },
        ],
        relatedUseCases: ['sales', 'slack', 'whatsapp'],
    },
    {
        slug: 'whatsapp',
        title: 'Voice Typing for WhatsApp',
        metaTitle: 'Voice Typing for WhatsApp — Send Polished Messages by Voice | Zavi AI',
        metaDescription: 'Use Zavi AI to send polished WhatsApp messages by voice. Speak normally and get clean text messages with translations or automatic emojis.',
        heroTitle: 'WhatsApp Messages, Without the Typing',
        heroSubtitle: 'Stop sending annoying voice notes. Speak natively to send readable, formatted text messages instead.',
        icon: '💬',
        problem: 'Voice notes on WhatsApp are inconvenient for recipients — they can\'t skim them or read them quietly. But typing long messages on a small glass screen is painfully slow. You\'re stuck choosing between speed for yourself or convenience for them.',
        solution: 'Zavi gives you the best of both worlds with instantaneous Darwin IPC loading. Speak naturally, and Zavi converts it to clean text with auto-contextual emojis. You can even toggle Live Translation to speak in Hindi and type in English.',
        howItWorks: [
            'Open any WhatsApp chat and activate the Zavi keyboard.',
            'Tap the Google Translate logo to toggle "Live Translation" between 15 target languages.',
            'Speak your message with the Emoji toggle active.',
            'Clean text appears with automatic context-aware emojis inserted (i.e. "That\'s amazing! 🤩").',
        ],
        benefits: [
            { title: 'Flow Sessions', description: 'Background audio stays warm for 5 minutes. After the first tap, subsequent mic taps start/stop instantly with zero app-switching.' },
            { title: 'Live Translation (15+ Languages)', description: 'Speak in German, French, Spanish, Hindi, or Chinese, and automatically type out perfect English.' },
            { title: 'Contextual Emojis', description: 'Enable the Emoji Toggle to allow the Gemini AI to automatically insert fun, context-aware emojis into casual chats.' },
            { title: 'Hold-to-Repeat Actions', description: 'Customizable Action Buttons on the bottom row allow you to hold Backspace for a rapid 50ms repeat delete to clear out lines instantly.' },
        ],
        exampleBefore: 'Hey so like I\'m running a bit late, um, probably gonna be there in like 20 minutes.',
        exampleAfter: 'Hey, I\'m running about 20 minutes late! See you soon. 🚗💨',
        targetAudience: ['Mobile-first communicators', 'Multilingual group chats', 'Busy parents', 'Anyone tired of voice notes'],
        faqItems: [
            { question: 'Does Zavi replace the WhatsApp keyboard?', answer: 'Zavi replaces your device\'s system keyboard. It defaults to a Number Pad or QWERTY, but the Mic button instantly jumps you to the Voice panel.' },
            { question: 'Can I speak in Hindi and type in English?', answer: 'Yes. Zavi supports 19 transcription languages and 15 live translation target languages, including Hindi to English.' },
            { question: 'Does it work on WhatsApp Web?', answer: 'Yes! Zavi is cross-platform. You can use it as a keyboard on your phone, or as a system-wide desktop listener on Mac, Windows, and Linux.' },
        ],
        relatedUseCases: ['email', 'slack', 'accessibility'],
    },
    {
        slug: 'students',
        title: 'Voice Typing for Students',
        metaTitle: 'Voice Typing for Students — Write Essays 4x Faster | Zavi AI',
        metaDescription: 'Students: write essays, take lecture notes, and run web searches with Zavi AI voice typing. Talk it out, get polished academic text.',
        heroTitle: 'Write Essays 4x Faster by Speaking',
        heroSubtitle: 'Turn lecture notes, essays, and web research into structured prose—just by speaking.',
        icon: '🎓',
        problem: 'Students spend hours transcribing lecture notes and fighting writer\'s block. Staring at a blank Google Doc is demoralizing. Bouncing between a browser array to search for quotes and back to an essay destroys focus and flow state.',
        solution: 'Zavi AI lets students dictate at the speed of speech. The AI clears out "ums" and restructures casual speech into crisp academic writing. With built-in Tavily Web Search, you can ask real-time questions directly into your document.',
        howItWorks: [
            'Open Google Docs, Notion, or Obsidian.',
            'Start speaking your raw thoughts into the microphone.',
            'Stuck on facts? Trigger the Voice Agent (Pro) and ask "What\'s the latest news on [topic]?"',
            'Zavi searches the web in real-time and speaks the result aloud via TTS.',
        ],
        benefits: [
            { title: 'Built-in Web Search (Pro)', description: 'Tavily Web Search allows you to run real-time queries via voice, letting you stay focused in your document while Zavi fetches facts.' },
            { title: 'Custom Snippets', description: 'Create trigger phrases that expand into massive academic blocks. Say "my standard intro", and Zavi pastes your predefined text.' },
            { title: 'Session History', description: 'Accidentally deleted a paragraph? Browse your past voice sessions in the Zavi app Dashboard, tap to copy, and paste it back.' },
            { title: 'Better Grammar', description: 'AI automatically fixes advanced grammar syntax, saving hours during the proofreading loop.' },
        ],
        exampleBefore: 'So basically the French Revolution started because, um, there was a lot of inequality, like the third estate was paying all the taxes.',
        exampleAfter: 'The French Revolution was primarily driven by deep social inequality, as the Third Estate bore the entire tax burden.',
        targetAudience: ['University students', 'Journalists', 'Graduate researchers', 'ESL students'],
        faqItems: [
            { question: 'Is Zavi free for students?', answer: 'Yes, Zavi offers a generous free plan of 1,000 words/day. Pro ($7.99/month) unlocks unlimited usage, the Voice Agent, and Web Search functionality.' },
            { question: 'Does Zavi work offline?', answer: 'No, Zavi relies on a gRPC Bidirectional Streaming cloud connection to process real-time transcripts and connect to the Gemini LLM for grammar generation.' },
        ],
        relatedUseCases: ['writers', 'accessibility', 'whatsapp'],
    },
    {
        slug: 'accessibility',
        title: 'Voice Typing for Accessibility (RSI)',
        metaTitle: 'Voice Typing for RSI & Carpal Tunnel — Hands-Free OS Control | Zavi AI',
        metaDescription: 'Reduce hand strain with Zavi AI. Ideal for RSI and carpal tunnel. Type, send emails, and control Slack totally hands-free.',
        heroTitle: 'Type Without Your Hands',
        heroSubtitle: 'Professional-quality writing and software control without touching a mouse or keyboard.',
        icon: '♿',
        problem: 'Millions of users suffer from Repetitive Strain Injury (RSI) or Carpal Tunnel Syndrome, making typing painful. Traditional voice typing requires extensive manual formatting and editing afterward—completely defeating the purpose of a hands-free tool.',
        solution: 'Zavi AI eliminates the editing phase entirely via Zero-Prompt text formatting. Furthermore, the Zavi Voice Agent acts as an operating system layer, allowing you to execute tasks across connected apps without ever touching the screen.',
        howItWorks: [
            'Launch the Zavi desktop app or assign it to a physical shortcut key.',
            'Tap the Voice Agent (paperplane) icon.',
            'Say: "Post to Slack channel #updates that I am taking a sick day."',
            'Zavi connects to your Slack via OAuth and executes the post entirely hands-free.',
        ],
        benefits: [
            { title: 'Zero Hand Strain', description: 'Dictate perfectly formatted emails, Slack messages, and Google Docs without utilizing a traditional keyboard.' },
            { title: 'Connected Services (Pro)', description: 'Route voice commands safely across Gmail, Slack, GitHub, LinkedIn, Google Calendar, and Drive using an advanced multi-turn tool calling loop.' },
            { title: 'Stale State Recovery', description: 'If the system hangs, tap the status text ("Enhancing...") to instantly Tap-to-Cancel and reset the connection without forcing app restarts.' },
            { title: 'Every App, Every Platform', description: 'Works globally across Android, macOS, Windows, and Linux as a localized input framework.' },
        ],
        exampleBefore: '[Cannot type due to wrist pain. Basic dictation outputs a giant uncapitalized block of text requiring editing.]',
        exampleAfter: 'I will be working from home tomorrow due to a morning doctor\'s appointment. I will be online by noon.',
        targetAudience: ['RSI sufferers', 'Occupational therapy patients', 'Screen-reader users', 'Mobility limited professionals'],
        faqItems: [
            { question: 'Is Zavi better than Dragon for accessibility?', answer: 'Yes. At just $7.99/mo, Zavi works across your entire cross-platform software stack, utilizes LLMs to actively restructure grammar (which Dragon cannot do), and executes multi-turn app functions via the Voice Agent.' },
            { question: 'Can I use Zavi all day without limits?', answer: 'The Pro tier provides unlimited word counts perfectly suited for users who rely entirely on voice as their primary method of digital input.' },
        ],
        relatedUseCases: ['engineers', 'slack'],
    },
    {
        slug: 'slack',
        title: 'Voice Typing for Slack & Teams',
        metaTitle: 'Voice Typing for Slack & Microsoft Teams — Message Faster | Zavi AI',
        metaDescription: 'Send polished Slack and Microsoft Teams messages by voice. Stop typing context switches and collaborate instantly via Voice Agent.',
        heroTitle: 'Slack & Teams, at the Speed of Speech',
        heroSubtitle: 'Respond to workspace messages instantly, route GitHub PR links, and update your status via voice.',
        icon: '💼',
        problem: 'Knowledge workers spend 2+ hours daily inside Slack. Quick messages become a massive time sink when you factor in typing status updates, context switching, and project debates—especially on mobile keyboards.',
        solution: 'Zavi AI lets you interact with Slack at the speed of thought. Speak your response naturally to generate perfectly formatted text. With Zavi Pro, you can entirely bypass the Slack UI by issuing Voice Agent actions externally.',
        howItWorks: [
            'Open Slack, Discord, or Microsoft Teams.',
            'Tap into the text field, select your Tone (Chat vs Professional), and trigger the mic.',
            'Or, use the Voice Agent anywhere: "Tell Himanshu on Slack that the new API deployment is live."',
            'Wait for the TTS completion chime. The message is sent.',
        ],
        benefits: [
            { title: 'Tone Selection', description: 'Switch between the "Chat (bubbles)" tone for quick DMs and the "Professional (briefcase)" tone for company-wide #general announcements.' },
            { title: 'Connected Slack Services (Pro)', description: 'Connect your Slack account securely via OAuth in the Zavi Dashboard. The Voice Agent seamlessly routes commands to channels and users.' },
            { title: 'Bring Your Own Keys (BYOK)', description: 'Power users can inject their personal OpenAI, Claude, or Gemini API keys to increase their Voice Agent\'s intelligence layer securely.' },
            { title: 'Darwin IPC Loading', description: 'Mobile background audio stays warm. Instantly drop in and out of voice typing while jumping between Slack threads—with zero software delay.' },
        ],
        exampleBefore: 'Hey team, um, I just finished reviewing the design mockups and they look good, um, but we need to update the palette on the landing page.',
        exampleAfter: 'Hey team, I just finished reviewing the design mockups—they look great. One minor thing: we need to update the color palette on the landing page.',
        targetAudience: ['Remote workers', 'Product Managers', 'Engineering Leads', 'Startup Founders'],
        faqItems: [
            { question: 'Are my Slack messages stored on your servers?', answer: 'No. Zavi operates under a strict Privacy-First model. Audio is processed via gRPC Bidirectional streaming in real-time and immediately deleted. Conversations are never trained on.' },
            { question: 'Can I use Zavi for Slack threads?', answer: 'Yes! Zavi replaces the system keyboard natively, so it operates powerfully in DMs, threads, and the global Slack search bar.' },
        ],
        relatedUseCases: ['engineers', 'email', 'product'],
    },
    {
        slug: 'writers',
        title: 'Voice Typing for Writers & Creators',
        metaTitle: 'Voice Typing for Writers — Crush Writer\'s Block | Zavi AI',
        metaDescription: 'The ultimate AI writing assistant for authors and copywriters. Rewrite sections, change tones, and overcome the blank page with Magic Wand voice commands.',
        heroTitle: 'Banish Writer\'s Block Forever',
        heroSubtitle: 'Transform your raw thoughts into beautifully structured prose, or command the AI to rewrite existing paragraphs instantly.',
        icon: '✍️',
        problem: 'Staring at a blank page is the biggest hurdle for creative professionals, authors, and copywriters. When the words finally come out, you often spend far more time editing rhythm and grammar than producing raw content.',
        solution: 'Zavi AI allows you to stream-of-consciousness dictate your thoughts into physical reality. If the paragraph isn\'t quite right, trigger the Zavi Magic Wand and say: "Make this sound more poetic and witty." Zavi rewrites the field in real-time.',
        howItWorks: [
            'Open Notion, Scrivener, Word, or Ulysses.',
            'Dictate your rough draft thoughts at 150 WPM.',
            'Highlight a paragraph, tap the Magic Wand icon.',
            'Say: "Shorten this and make it sound punchier." Watch the Gemini AI reconstruct your drafted sentence.',
        ],
        benefits: [
            { title: 'Magic Wand Editing (Pro)', description: 'Change the direction of your writing instantly without taking your hands off the keyboard. Describe your rewrite, and the Wand handles the syntax.' },
            { title: 'Custom Personal Dictionary', description: 'Working on a fantasy novel? Add your highly unique character names and locations to the Zavi dictionary so the speech-to-text engine never misspells them.' },
            { title: 'Dynamic Tone Controls', description: 'Switch the underlying text engine from "Casual" to "Witty (theater masks)" to instantly change how the AI cleans up your raw speech transcripts.' },
            { title: 'History Archives', description: 'Access up to 50 previous dictation sessions via the Zavi Dashboard logic. Never lose a brilliant idea even if your Word doc crashes.' },
        ],
        exampleBefore: '[Using the Magic Wand on a paragraph]: "Make this sound like a formal Victorian detective novel."',
        exampleAfter: 'The dense fog hung low over the cobblestones of Baker Street, obscuring the faint, hurried footsteps of our elusive suspect.',
        targetAudience: ['Authors', 'Copywriters', 'Bloggers', 'Content Creators'],
        faqItems: [
            { question: 'Does the Magic Wand replace my text completely?', answer: 'Yes! Zavi highlights your active text block and utilizes its permissions to hot-swap the old text with your newly commanded AI variation.' },
            { question: 'Can I bring my own LLM API key?', answer: 'Yes. If you prefer the writing style of Claude 3.5 Sonnet over Gemini, you can securely plug in your personal API key into the Settings Dashboard.' },
        ],
        relatedUseCases: ['students', 'email'],
    },
    {
        slug: 'sales',
        title: 'Voice Typing for Sales & CRM',
        metaTitle: 'Voice Typing for Sales Reps — Update Salesforce Faster | Zavi AI',
        metaDescription: 'Update CRM fields, draft LinkedIn sequences, and write follow-up emails instantly. Never fall behind on data entry again.',
        heroTitle: 'Crush Quotas, Not Data Entry',
        heroSubtitle: 'Dictate pristine meeting notes directly into Hubspot or Salesforce. Connect LinkedIn and Gmail to automate your follow-ups.',
        icon: '📈',
        problem: 'Sales representatives generate revenue by talking to prospects, but they lose 30% of their day to tedious CRM hygiene, writing follow-up emails, and organizing meeting transcripts.',
        solution: 'Zavi acts as a pocket sales assistant. Dictate highly detailed, grammatically perfect meeting recaps into Salesforce fields in seconds. Leverage the Voice Agent to execute automated LinkedIn connections and prospect emails hands-free while driving.',
        howItWorks: [
            'Drive away from an on-site client meeting.',
            'Open your CRM app, tap the mic, and brain-dump the entire conversation.',
            'Zavi removes every "um" and "ah", generating a perfect, bulleted recap.',
            'Tap the Voice Agent: "Send an email to Sarah thanking her for the meeting and attaching the pricing doc from Google Drive."',
        ],
        benefits: [
            { title: 'Connected Google Suite (Pro)', description: 'Zavi securely interfaces with Google Drive, Docs, Contacts, and Calendar. Ask Zavi to pull the latest pricing PDF and email it immediately.' },
            { title: 'LinkedIn Integration (Pro)', description: 'Use the Voice Agent to locate a prospect on LinkedIn and send a customized connection request based entirely on your vocal instructions.' },
            { title: 'Infinite Stream Rotation', description: 'Dictating a 15-minute prospect interaction? Zavi\'s 1.5s bridging buffer seamlessly bypasses traditional 5-minute transcription limits.' },
            { title: 'Custom Snippets', description: 'Setup "trigger phrases" for your most common objections. Say "pricing objection snippet", and Zavi injects your 3-paragraph approved rebuttal.' },
        ],
        exampleBefore: 'Voice Agent Command: "Look up John Smith at Acme Corp on LinkedIn and send him a message asking to connect about the Q3 SaaS RFP."',
        exampleAfter: '[TTS Chime] "I have located John Smith at Acme Corp and submitted the connection request on LinkedIn with your referenced message."',
        targetAudience: ['Account Executives', 'SDRs', 'Real Estate Agents', 'Founders'],
        faqItems: [
            { question: 'Does Zavi work in Salesforce and Hubspot mobile apps?', answer: 'Yes. By acting as the unified system keyboard, Zavi functions perfectly inside every CRM UI text field.' },
            { question: 'Is client data safe?', answer: 'Absolutely. Zavi explicitly does not train on user audio clips, and all gRPC pipeline data is immediately scrubbed from RAM post-processing. See our SOC-2 compliant Privacy breakdown.' },
        ],
        relatedUseCases: ['email', 'slack', 'product'],
    },
    {
        slug: 'medical',
        title: 'Voice Typing for Medical Pros',
        metaTitle: 'Medical Dictation Software for Doctors — Private & Fast | Zavi AI',
        metaDescription: 'HIPAA-compliant, highly-accurate AI voice dictation for EMRs. Dictate patient charts without the massive legacy enterprise software costs.',
        heroTitle: 'Charting, Completely Cured',
        heroSubtitle: 'Dictate complex medical assessments cleanly into any EMR system with absolute local-data privacy.',
        icon: '⚕️',
        problem: 'Doctors and nurses spend nearly 2 hours on EHR data entry for every 1 hour of patient care. Legacy enterprise "medical dictation" software is sluggish, traps you into monolithic contracts ($2000+/year), and requires extensive manual correction.',
        solution: 'Zavi AI operates agnostically across Epic, Cerner, or any web-based EMR. Dictating medical shorthand instantly triggers Zavi\'s AI to format the raw audio into structured, grammatically perfect SOAP notes—starting at just $7.99/mo.',
        howItWorks: [
            'Launch Zavi on your workstation alongside your web-based EHR.',
            'Dictate your Subjective, Objective, Assessment, and Plan notes quickly.',
            'If you need to reformat, use the Magic Wand and say "Format this as a bulleted medical chart".',
            'Zavi executes the transformation securely.',
        ],
        benefits: [
            { title: 'Privacy First Architecture', description: 'Patient Audio data is immediately destroyed post-transcription. Ensure rapid compliance with strict privacy-forward engineering.' },
            { title: 'Advanced Dictionary', description: 'Add your precise pharmaceutical nomenclatures, localized physician names, and esoteric diagnoses into Zavi\'s custom dictionary cache to guarantee 100% hit rates.' },
            { title: 'Magic Wand Formatting (Pro)', description: 'Turn rambling patient interactions into strictly formatted, highly-legible bulleted lists inside the EHR notes section with one Voice Command.' },
            { title: 'Action Buttons', description: 'Quickly undo, redo, or execute rapid Backspace deletions via the customized Action Bottom Row without touching the mouse.' },
        ],
        exampleBefore: 'The patient presents with um mild abdominal pain radiating to the back started about two days ago no nausea no vomiting heartbeat is regular.',
        exampleAfter: 'The patient presents with mild abdominal pain radiating to the back. Onset was approximately two days ago. Patient denies nausea and vomiting. Heart rate is regular.',
        targetAudience: ['Physicians', 'Nurses', 'Therapists', 'Veterinarians', 'Private Practices'],
        faqItems: [
            { question: 'Is Zavi HIPAA compliant?', answer: 'Zavi operates with strict No-Data-Retention policies. Enterprise implementations can be localized to completely sandbox the Gemini engine to your custom BAA cloud environment.' },
            { question: 'Can I use this on iPad Mini rounds?', answer: 'Yes! Zavi functions as a system-wide custom keyboard on iOS and Android tablet architectures.' },
        ],
        relatedUseCases: ['legal', 'email', 'accessibility'],
    },
    {
        slug: 'legal',
        title: 'Voice Typing for Legal Teams',
        metaTitle: 'Legal Dictation Software — Fast Legal Transcription | Zavi AI',
        metaDescription: 'Draft complex contracts, send rapid partner emails, and log billable hours via seamless, private cross-platform voice transcription.',
        heroTitle: 'Draft Briefs & Log Hours by Voice',
        heroSubtitle: 'Move faster than opposing counsel. Dictate complex legal documents with perfect syntax, formatting, and absolute privacy.',
        icon: '⚖️',
        problem: 'Lawyers are paralyzed by the compounding hours of drafting briefs, answering associate emails, and logging tiny increments of billable time into clunky practice management software.',
        solution: 'Zavi AI operates seamlessly inside Clio, LexisNexis, Word, and Outlook. Speak out multi-page legal arguments, while Zavi handles the punctuation, Latin phrasing, and complex structural formatting via the "Professional" tone engine.',
        howItWorks: [
            'Load up your legal brief document in Microsoft Word.',
            'Set Zavi\'s Tone selector to "Professional (Briefcase)".',
            'Dictate your arguments; Zavi immediately corrects "ums", hesitations, and disjointed logic.',
            'Use the Voice Agent (Pro) to say: "Log a 15-minute billable task in Notion for the Smith Case."',
        ],
        benefits: [
            { title: 'The "Professional" Tone Engine', description: 'Automatically forces the AI to output highly formal, stiff, perfectly structured syntax suitable for legal briefs and court filings.' },
            { title: 'Voice Agent OS (Pro)', description: 'Utilize deep API connections to draft documents in Google Docs or organize items in Notion purely through conversational commands.' },
            { title: 'Absolute Confidentiality', description: 'Attorney-client privilege is preserved via Zavi\'s no-retention streaming framework. The audio is instantly destroyed upon text injection.' },
            { title: 'Multi-Ring Mic Feedback', description: 'Animated visual indicators confirm the exact pipeline state (listening, connecting, recording) so you never miss a recorded thought.' },
        ],
        exampleBefore: '[Reviewing evidence] "Uh, state that the plaintiff clearly violated section 4 by, um, failing to deliver the documents on time as stipulated in the contract."',
        exampleAfter: 'The plaintiff committed a clear violation of Section 4 by failing to deliver the stipulated documents within the agreed-upon timeframe outlined in the contract.',
        targetAudience: ['Attorneys', 'Paralegals', 'Legal Assistants', 'Consultants'],
        faqItems: [
            { question: 'Can it understand Latin legal phrases?', answer: 'Yes, the underlying Gemini/Claude LLM models are heavily trained on legal corpi. Further accuracy can be achieved by injecting terms into the Zavi Custom Dictionary.' },
            { question: 'Does it run standalone on Mac?', answer: 'Yes, Zavi acts as a localized desktop widget on macOS and Windows, enabling voice injection into any native app without copy-pasting.' },
        ],
        relatedUseCases: ['medical', 'sales', 'slack'],
    },
    {
        slug: 'engineers',
        title: 'Voice Typing for Engineers',
        metaTitle: 'Voice Input for Software Engineers — Code & Communicate | Zavi AI',
        metaDescription: 'Execute GitHub workflows, write Jira tickets, and dictate architectural design docs 4x faster using Zavi AI Developer integrations.',
        heroTitle: 'Code is Fast. Documentation is Slow.',
        heroSubtitle: 'Stop context-switching. Update Jira tickets, merge PRs, and draft technical specs purely via Voice Agent.',
        icon: '💻',
        problem: 'Engineers despise writing documentation or updating Jira. The physical act of moving hands off the IDE shortcuts to type out a 300-word PR description breaks flow-state and ruins productivity.',
        solution: 'Zavi acts as your personal Junior Dev Assistant. Dictate complex technical architecture into Confluence at 150 WPM. With Zavi Pro, leverage the GitHub integration to execute workflow commands hands-free.',
        howItWorks: [
            'Finish writing a complex module inside VSCode.',
            'Tap the Voice Agent (Pro): "Create a new pull request on GitHub for the auth-refactor branch and summarize the JWT changes."',
            'Zavi triggers the OAuth pipeline, reads the branch context, and executes the PR.',
            'You never took your hands off the keyboard.',
        ],
        benefits: [
            { title: 'GitHub Integration (Pro)', description: 'Securely link your GitHub account. Issue Voice Agent commands to create PRs, summarize diffs, assign reviewers, or check CI/CD status.' },
            { title: 'BYOK (Bring Your Own Key)', description: 'Plug in your own OpenAI `gpt-4o` or Anthropic `claude-3-5-sonnet` API keys to supercharge the backend reasoning capabilities for complex coding workflows.' },
            { title: 'Developer Dictionary', description: 'Add your custom microservice names (e.g. `auth-worker-v2`) and tech-stack terminology into the local dictionary for perfect speech recognition.' },
            { title: 'Haptic Feedback Transitions', description: 'Contextual haptics and TTS chimes let you know exactly when a multi-turn Voice Agent sequence has completed in the background.' },
        ],
        exampleBefore: 'Voice Agent: "Check if the frontend tests passed on my latest UI branch."',
        exampleAfter: '[TTS Output] "The GitHub Actions CI/CD pipeline for branch ui-refactor completed successfully 3 minutes ago."',
        targetAudience: ['Software Engineers', 'DevOps', 'Product Managers', 'CTOs'],
        faqItems: [
            { question: 'Does Zavi inject actual code?', answer: 'Zavi is optimized for natural language compilation (documentation, Slack, emails), but you can trigger the Magic Wand "Rewrite as Python code" to generate boilerplate structures inside your IDE.' },
            { question: 'Is my employer\'s source code safe?', answer: 'Yes. Zavi only accesses GitHub data explicitly requested by the Voice Agent during a specific multi-turn tool call, and no data is retained or utilized for model training.' },
        ],
        relatedUseCases: ['product', 'slack', 'accessibility'],
    }
];

export function getUseCaseBySlug(slug: string): UseCase | undefined {
    return useCases.find(uc => uc.slug === slug);
}
