export interface UseCase {
    slug: string;
    title: string;
    metaTitle: string;
    metaDescription: string;
    heroTitle: string;
    heroSubtitle: string;
    icon: string;
    problem: string;
    solution: string;
    howItWorks: string[];
    benefits: { title: string; description: string }[];
    exampleBefore: string;
    exampleAfter: string;
    targetAudience: string[];
    faqItems: { question: string; answer: string }[];
    relatedUseCases: string[];
}

export const useCases: UseCase[] = [
    {
        slug: 'email',
        title: 'Voice Typing for Email',
        metaTitle: 'Voice Typing for Email — Draft Emails 4x Faster with Zavi AI',
        metaDescription: 'Use Zavi AI to draft professional emails by voice. Speak naturally and get polished, grammar-perfect emails in Gmail, Outlook, and every email app. Free download.',
        heroTitle: 'Draft Professional Emails by Voice',
        heroSubtitle: 'Speak naturally. Zavi removes filler words, fixes grammar, and delivers ready-to-send emails in seconds.',
        icon: '✉️',
        problem: 'The average professional sends 40+ emails per day and spends 2.5 hours writing them. Typing on mobile is slow (38 WPM), and even desktop typing (40 WPM) can\'t keep up with the pace of modern communication. The result: rushed, error-filled emails or a growing inbox of unread messages.',
        solution: 'Zavi AI lets you dictate emails at 150 WPM — 4x faster than typing. With the Pro "Magic Wand" feature, you can even say "make this more professional" or "rewrite as bullet points" to instantly transform a rough draft into an executive-ready message.',
        howItWorks: [
            'Open Gmail, Outlook, or any email app and tap the Zavi mic (or hold action button).',
            'Speak your email naturally — include any "umms" or pauses.',
            'Need an edit? Tap the Magic Wand and say "make this sound friendlier".',
            'Need to send it hands-free? Use the Voice Agent: "Send David an email about Thursday\'s meeting".',
        ],
        benefits: [
            { title: 'Magic Wand Editing (Pro)', description: 'Transform any text just by describing the changes. Say "shorten this" or "fix grammar", and the Gemini LLM rewrites the field.' },
            { title: 'Tone Selection', description: 'Cycle through 4 tones instantly (Professional, Casual, Chat, Witty) by tapping the tone icon before you dictate.' },
            { title: 'Zero Hand Strain', description: 'The advanced Voice Agent routes multi-turn commands through your connected Gmail via OAuth—no typing needed.' },
            { title: 'Dictionary Personalization', description: 'Add your custom coworker names like "Daenerys" or "Siobhan" so the AI never mishears them.' },
        ],
        exampleBefore: 'Um, hey John, so I was thinking, uh, we should probably like meet up next Tuesday, you know, to go over the Q3 numbers.',
        exampleAfter: 'Hi John, I\'d like to schedule a meeting next Tuesday to review the Q3 numbers. Does that work for you?',
        targetAudience: ['Account Executives', 'CEOs', 'Remote workers', 'Customer support teams', 'Anyone who writes 10+ emails/day'],
        faqItems: [
            { question: 'Does Zavi work in Gmail?', answer: 'Yes. Zavi works as a system-wide keyboard, so it works perfectly across Gmail, Outlook, Apple Mail, and Yahoo Mail.' },
            { question: 'What does the Voice Agent do?', answer: 'With Zavi Pro, you can tap the paperplane icon and say "Send David an email...". The Voice Agent executes a multi-turn tool-calling loop through your connected Gmail account to send the message for you.' },
            { question: 'Can I dictate long emails?', answer: 'Yes! Zavi bypasses standard 5-minute transcription constraints via Stream Rotation, allowing seamless and infinite dictation sessions.' },
        ],
        relatedUseCases: ['sales', 'slack', 'whatsapp'],
    },
    {
        slug: 'whatsapp',
        title: 'Voice Typing for WhatsApp',
        metaTitle: 'Voice Typing for WhatsApp — Send Polished Messages by Voice | Zavi AI',
        metaDescription: 'Use Zavi AI to send polished WhatsApp messages by voice. Speak normally and get clean text messages with translations or automatic emojis.',
        heroTitle: 'WhatsApp Messages, Without the Typing',
        heroSubtitle: 'Stop sending annoying voice notes. Speak natively to send readable, formatted text messages instead.',
        icon: '💬',
        problem: 'Voice notes on WhatsApp are inconvenient for recipients — they can\'t skim them or read them quietly. But typing long messages on a small glass screen is painfully slow. You\'re stuck choosing between speed for yourself or convenience for them.',
        solution: 'Zavi gives you the best of both worlds with instantaneous Darwin IPC loading. Speak naturally, and Zavi converts it to clean text with auto-contextual emojis. You can even toggle Live Translation to speak in Hindi and type in English.',
        howItWorks: [
            'Open any WhatsApp chat and activate the Zavi keyboard.',
            'Tap the Google Translate logo to toggle "Live Translation" between 15 target languages.',
            'Speak your message with the Emoji toggle active.',
            'Clean text appears with automatic context-aware emojis inserted (i.e. "That\'s amazing! 🤩").',
        ],
        benefits: [
            { title: 'Flow Sessions', description: 'Background audio stays warm for 5 minutes. After the first tap, subsequent mic taps start/stop instantly with zero app-switching.' },
            { title: 'Live Translation (15+ Languages)', description: 'Speak in German, French, Spanish, Hindi, or Chinese, and automatically type out perfect English.' },
            { title: 'Contextual Emojis', description: 'Enable the Emoji Toggle to allow the Gemini AI to automatically insert fun, context-aware emojis into casual chats.' },
            { title: 'Hold-to-Repeat Actions', description: 'Customizable Action Buttons on the bottom row allow you to hold Backspace for a rapid 50ms repeat delete to clear out lines instantly.' },
        ],
        exampleBefore: 'Hey so like I\'m running a bit late, um, probably gonna be there in like 20 minutes.',
        exampleAfter: 'Hey, I\'m running about 20 minutes late! See you soon. 🚗💨',
        targetAudience: ['Mobile-first communicators', 'Multilingual group chats', 'Busy parents', 'Anyone tired of voice notes'],
        faqItems: [
            { question: 'Does Zavi replace the WhatsApp keyboard?', answer: 'Zavi replaces your device\'s system keyboard. It defaults to a Number Pad or QWERTY, but the Mic button instantly jumps you to the Voice panel.' },
            { question: 'Can I speak in Hindi and type in English?', answer: 'Yes. Zavi supports 19 transcription languages and 15 live translation target languages, including Hindi to English.' },
            { question: 'Does it work on WhatsApp Web?', answer: 'Yes! Zavi is cross-platform. You can use it as a keyboard on your phone, or as a system-wide desktop listener on Mac, Windows, and Linux.' },
        ],
        relatedUseCases: ['email', 'slack', 'accessibility'],
    },
    {
        slug: 'students',
        title: 'Voice Typing for Students',
        metaTitle: 'Voice Typing for Students — Write Essays 4x Faster | Zavi AI',
        metaDescription: 'Students: write essays, take lecture notes, and run web searches with Zavi AI voice typing. Talk it out, get polished academic text.',
        heroTitle: 'Write Essays 4x Faster by Speaking',
        heroSubtitle: 'Turn lecture notes, essays, and web research into structured prose—just by speaking.',
        icon: '🎓',
        problem: 'Students spend hours transcribing lecture notes and fighting writer\'s block. Staring at a blank Google Doc is demoralizing. Bouncing between a browser array to search for quotes and back to an essay destroys focus and flow state.',
        solution: 'Zavi AI lets students dictate at the speed of speech. The AI clears out "ums" and restructures casual speech into crisp academic writing. With built-in Tavily Web Search, you can ask real-time questions directly into your document.',
        howItWorks: [
            'Open Google Docs, Notion, or Obsidian.',
            'Start speaking your raw thoughts into the microphone.',
            'Stuck on facts? Trigger the Voice Agent (Pro) and ask "What\'s the latest news on [topic]?"',
            'Zavi searches the web in real-time and speaks the result aloud via TTS.',
        ],
        benefits: [
            { title: 'Built-in Web Search (Pro)', description: 'Tavily Web Search allows you to run real-time queries via voice, letting you stay focused in your document while Zavi fetches facts.' },
            { title: 'Custom Snippets', description: 'Create trigger phrases that expand into massive academic blocks. Say "my standard intro", and Zavi pastes your predefined text.' },
            { title: 'Session History', description: 'Accidentally deleted a paragraph? Browse your past voice sessions in the Zavi app Dashboard, tap to copy, and paste it back.' },
            { title: 'Better Grammar', description: 'AI automatically fixes advanced grammar syntax, saving hours during the proofreading loop.' },
        ],
        exampleBefore: 'So basically the French Revolution started because, um, there was a lot of inequality, like the third estate was paying all the taxes.',
        exampleAfter: 'The French Revolution was primarily driven by deep social inequality, as the Third Estate bore the entire tax burden.',
        targetAudience: ['University students', 'Journalists', 'Graduate researchers', 'ESL students'],
        faqItems: [
            { question: 'Is Zavi free for students?', answer: 'Yes, Zavi offers a generous free plan of 1,000 words/day. Pro ($7.99/month) unlocks unlimited usage, the Voice Agent, and Web Search functionality.' },
            { question: 'Does Zavi work offline?', answer: 'No, Zavi relies on a gRPC Bidirectional Streaming cloud connection to process real-time transcripts and connect to the Gemini LLM for grammar generation.' },
        ],
        relatedUseCases: ['writers', 'accessibility', 'whatsapp'],
    },
    {
        slug: 'accessibility',
        title: 'Voice Typing for Accessibility (RSI)',
        metaTitle: 'Voice Typing for RSI & Carpal Tunnel — Hands-Free OS Control | Zavi AI',
        metaDescription: 'Reduce hand strain with Zavi AI. Ideal for RSI and carpal tunnel. Type, send emails, and control Slack totally hands-free.',
        heroTitle: 'Type Without Your Hands',
        heroSubtitle: 'Professional-quality writing and software control without touching a mouse or keyboard.',
        icon: '♿',
        problem: 'Millions of users suffer from Repetitive Strain Injury (RSI) or Carpal Tunnel Syndrome, making typing painful. Traditional voice typing requires extensive manual formatting and editing afterward—completely defeating the purpose of a hands-free tool.',
        solution: 'Zavi AI eliminates the editing phase entirely via Zero-Prompt text formatting. Furthermore, the Zavi Voice Agent acts as an operating system layer, allowing you to execute tasks across connected apps without ever touching the screen.',
        howItWorks: [
            'Launch the Zavi desktop app or assign it to a physical shortcut key.',
            'Tap the Voice Agent (paperplane) icon.',
            'Say: "Post to Slack channel #updates that I am taking a sick day."',
            'Zavi connects to your Slack via OAuth and executes the post entirely hands-free.',
        ],
        benefits: [
            { title: 'Zero Hand Strain', description: 'Dictate perfectly formatted emails, Slack messages, and Google Docs without utilizing a traditional keyboard.' },
            { title: 'Connected Services (Pro)', description: 'Route voice commands safely across Gmail, Slack, GitHub, LinkedIn, Google Calendar, and Drive using an advanced multi-turn tool calling loop.' },
            { title: 'Stale State Recovery', description: 'If the system hangs, tap the status text ("Enhancing...") to instantly Tap-to-Cancel and reset the connection without forcing app restarts.' },
            { title: 'Every App, Every Platform', description: 'Works globally across Android, macOS, Windows, and Linux as a localized input framework.' },
        ],
        exampleBefore: '[Cannot type due to wrist pain. Basic dictation outputs a giant uncapitalized block of text requiring editing.]',
        exampleAfter: 'I will be working from home tomorrow due to a morning doctor\'s appointment. I will be online by noon.',
        targetAudience: ['RSI sufferers', 'Occupational therapy patients', 'Screen-reader users', 'Mobility limited professionals'],
        faqItems: [
            { question: 'Is Zavi better than Dragon for accessibility?', answer: 'Yes. At just $7.99/mo, Zavi works across your entire cross-platform software stack, utilizes LLMs to actively restructure grammar (which Dragon cannot do), and executes multi-turn app functions via the Voice Agent.' },
            { question: 'Can I use Zavi all day without limits?', answer: 'The Pro tier provides unlimited word counts perfectly suited for users who rely entirely on voice as their primary method of digital input.' },
        ],
        relatedUseCases: ['engineers', 'slack'],
    },
    {
        slug: 'slack',
        title: 'Voice Typing for Slack & Teams',
        metaTitle: 'Voice Typing for Slack & Microsoft Teams — Message Faster | Zavi AI',
        metaDescription: 'Send polished Slack and Microsoft Teams messages by voice. Stop typing context switches and collaborate instantly via Voice Agent.',
        heroTitle: 'Slack & Teams, at the Speed of Speech',
        heroSubtitle: 'Respond to workspace messages instantly, route GitHub PR links, and update your status via voice.',
        icon: '💼',
        problem: 'Knowledge workers spend 2+ hours daily inside Slack. Quick messages become a massive time sink when you factor in typing status updates, context switching, and project debates—especially on mobile keyboards.',
        solution: 'Zavi AI lets you interact with Slack at the speed of thought. Speak your response naturally to generate perfectly formatted text. With Zavi Pro, you can entirely bypass the Slack UI by issuing Voice Agent actions externally.',
        howItWorks: [
            'Open Slack, Discord, or Microsoft Teams.',
            'Tap into the text field, select your Tone (Chat vs Professional), and trigger the mic.',
            'Or, use the Voice Agent anywhere: "Tell Himanshu on Slack that the new API deployment is live."',
            'Wait for the TTS completion chime. The message is sent.',
        ],
        benefits: [
            { title: 'Tone Selection', description: 'Switch between the "Chat (bubbles)" tone for quick DMs and the "Professional (briefcase)" tone for company-wide #general announcements.' },
            { title: 'Connected Slack Services (Pro)', description: 'Connect your Slack account securely via OAuth in the Zavi Dashboard. The Voice Agent seamlessly routes commands to channels and users.' },
            { title: 'Bring Your Own Keys (BYOK)', description: 'Power users can inject their personal OpenAI, Claude, or Gemini API keys to increase their Voice Agent\'s intelligence layer securely.' },
            { title: 'Darwin IPC Loading', description: 'Mobile background audio stays warm. Instantly drop in and out of voice typing while jumping between Slack threads—with zero software delay.' },
        ],
        exampleBefore: 'Hey team, um, I just finished reviewing the design mockups and they look good, um, but we need to update the palette on the landing page.',
        exampleAfter: 'Hey team, I just finished reviewing the design mockups—they look great. One minor thing: we need to update the color palette on the landing page.',
        targetAudience: ['Remote workers', 'Product Managers', 'Engineering Leads', 'Startup Founders'],
        faqItems: [
            { question: 'Are my Slack messages stored on your servers?', answer: 'No. Zavi operates under a strict Privacy-First model. Audio is processed via gRPC Bidirectional streaming in real-time and immediately deleted. Conversations are never trained on.' },
            { question: 'Can I use Zavi for Slack threads?', answer: 'Yes! Zavi replaces the system keyboard natively, so it operates powerfully in DMs, threads, and the global Slack search bar.' },
        ],
        relatedUseCases: ['engineers', 'email', 'product'],
    },
    {
        slug: 'writers',
        title: 'Voice Typing for Writers & Creators',
        metaTitle: 'Voice Typing for Writers — Crush Writer\'s Block | Zavi AI',
        metaDescription: 'The ultimate AI writing assistant for authors and copywriters. Rewrite sections, change tones, and overcome the blank page with Magic Wand voice commands.',
        heroTitle: 'Banish Writer\'s Block Forever',
        heroSubtitle: 'Transform your raw thoughts into beautifully structured prose, or command the AI to rewrite existing paragraphs instantly.',
        icon: '✍️',
        problem: 'Staring at a blank page is the biggest hurdle for creative professionals, authors, and copywriters. When the words finally come out, you often spend far more time editing rhythm and grammar than producing raw content.',
        solution: 'Zavi AI allows you to stream-of-consciousness dictate your thoughts into physical reality. If the paragraph isn\'t quite right, trigger the Zavi Magic Wand and say: "Make this sound more poetic and witty." Zavi rewrites the field in real-time.',
        howItWorks: [
            'Open Notion, Scrivener, Word, or Ulysses.',
            'Dictate your rough draft thoughts at 150 WPM.',
            'Highlight a paragraph, tap the Magic Wand icon.',
            'Say: "Shorten this and make it sound punchier." Watch the Gemini AI reconstruct your drafted sentence.',
        ],
        benefits: [
            { title: 'Magic Wand Editing (Pro)', description: 'Change the direction of your writing instantly without taking your hands off the keyboard. Describe your rewrite, and the Wand handles the syntax.' },
            { title: 'Custom Personal Dictionary', description: 'Working on a fantasy novel? Add your highly unique character names and locations to the Zavi dictionary so the speech-to-text engine never misspells them.' },
            { title: 'Dynamic Tone Controls', description: 'Switch the underlying text engine from "Casual" to "Witty (theater masks)" to instantly change how the AI cleans up your raw speech transcripts.' },
            { title: 'History Archives', description: 'Access up to 50 previous dictation sessions via the Zavi Dashboard logic. Never lose a brilliant idea even if your Word doc crashes.' },
        ],
        exampleBefore: '[Using the Magic Wand on a paragraph]: "Make this sound like a formal Victorian detective novel."',
        exampleAfter: 'The dense fog hung low over the cobblestones of Baker Street, obscuring the faint, hurried footsteps of our elusive suspect.',
        targetAudience: ['Authors', 'Copywriters', 'Bloggers', 'Content Creators'],
        faqItems: [
            { question: 'Does the Magic Wand replace my text completely?', answer: 'Yes! Zavi highlights your active text block and utilizes its permissions to hot-swap the old text with your newly commanded AI variation.' },
            { question: 'Can I bring my own LLM API key?', answer: 'Yes. If you prefer the writing style of Claude 3.5 Sonnet over Gemini, you can securely plug in your personal API key into the Settings Dashboard.' },
        ],
        relatedUseCases: ['students', 'email'],
    },
    {
        slug: 'sales',
        title: 'Voice Typing for Sales & CRM',
        metaTitle: 'Voice Typing for Sales Reps — Update Salesforce Faster | Zavi AI',
        metaDescription: 'Update CRM fields, draft LinkedIn sequences, and write follow-up emails instantly. Never fall behind on data entry again.',
        heroTitle: 'Crush Quotas, Not Data Entry',
        heroSubtitle: 'Dictate pristine meeting notes directly into Hubspot or Salesforce. Connect LinkedIn and Gmail to automate your follow-ups.',
        icon: '📈',
        problem: 'Sales representatives generate revenue by talking to prospects, but they lose 30% of their day to tedious CRM hygiene, writing follow-up emails, and organizing meeting transcripts.',
        solution: 'Zavi acts as a pocket sales assistant. Dictate highly detailed, grammatically perfect meeting recaps into Salesforce fields in seconds. Leverage the Voice Agent to execute automated LinkedIn connections and prospect emails hands-free while driving.',
        howItWorks: [
            'Drive away from an on-site client meeting.',
            'Open your CRM app, tap the mic, and brain-dump the entire conversation.',
            'Zavi removes every "um" and "ah", generating a perfect, bulleted recap.',
            'Tap the Voice Agent: "Send an email to Sarah thanking her for the meeting and attaching the pricing doc from Google Drive."',
        ],
        benefits: [
            { title: 'Connected Google Suite (Pro)', description: 'Zavi securely interfaces with Google Drive, Docs, Contacts, and Calendar. Ask Zavi to pull the latest pricing PDF and email it immediately.' },
            { title: 'LinkedIn Integration (Pro)', description: 'Use the Voice Agent to locate a prospect on LinkedIn and send a customized connection request based entirely on your vocal instructions.' },
            { title: 'Infinite Stream Rotation', description: 'Dictating a 15-minute prospect interaction? Zavi\'s 1.5s bridging buffer seamlessly bypasses traditional 5-minute transcription limits.' },
            { title: 'Custom Snippets', description: 'Setup "trigger phrases" for your most common objections. Say "pricing objection snippet", and Zavi injects your 3-paragraph approved rebuttal.' },
        ],
        exampleBefore: 'Voice Agent Command: "Look up John Smith at Acme Corp on LinkedIn and send him a message asking to connect about the Q3 SaaS RFP."',
        exampleAfter: '[TTS Chime] "I have located John Smith at Acme Corp and submitted the connection request on LinkedIn with your referenced message."',
        targetAudience: ['Account Executives', 'SDRs', 'Real Estate Agents', 'Founders'],
        faqItems: [
            { question: 'Does Zavi work in Salesforce and Hubspot mobile apps?', answer: 'Yes. By acting as the unified system keyboard, Zavi functions perfectly inside every CRM UI text field.' },
            { question: 'Is client data safe?', answer: 'Absolutely. Zavi explicitly does not train on user audio clips, and all gRPC pipeline data is immediately scrubbed from RAM post-processing. See our SOC-2 compliant Privacy breakdown.' },
        ],
        relatedUseCases: ['email', 'slack', 'product'],
    },
    {
        slug: 'medical',
        title: 'Voice Typing for Medical Pros',
        metaTitle: 'Medical Dictation Software for Doctors — Private & Fast | Zavi AI',
        metaDescription: 'HIPAA-compliant, highly-accurate AI voice dictation for EMRs. Dictate patient charts without the massive legacy enterprise software costs.',
        heroTitle: 'Charting, Completely Cured',
        heroSubtitle: 'Dictate complex medical assessments cleanly into any EMR system with absolute local-data privacy.',
        icon: '⚕️',
        problem: 'Doctors and nurses spend nearly 2 hours on EHR data entry for every 1 hour of patient care. Legacy enterprise "medical dictation" software is sluggish, traps you into monolithic contracts ($2000+/year), and requires extensive manual correction.',
        solution: 'Zavi AI operates agnostically across Epic, Cerner, or any web-based EMR. Dictating medical shorthand instantly triggers Zavi\'s AI to format the raw audio into structured, grammatically perfect SOAP notes—starting at just $7.99/mo.',
        howItWorks: [
            'Launch Zavi on your workstation alongside your web-based EHR.',
            'Dictate your Subjective, Objective, Assessment, and Plan notes quickly.',
            'If you need to reformat, use the Magic Wand and say "Format this as a bulleted medical chart".',
            'Zavi executes the transformation securely.',
        ],
        benefits: [
            { title: 'Privacy First Architecture', description: 'Patient Audio data is immediately destroyed post-transcription. Ensure rapid compliance with strict privacy-forward engineering.' },
            { title: 'Advanced Dictionary', description: 'Add your precise pharmaceutical nomenclatures, localized physician names, and esoteric diagnoses into Zavi\'s custom dictionary cache to guarantee 100% hit rates.' },
            { title: 'Magic Wand Formatting (Pro)', description: 'Turn rambling patient interactions into strictly formatted, highly-legible bulleted lists inside the EHR notes section with one Voice Command.' },
            { title: 'Action Buttons', description: 'Quickly undo, redo, or execute rapid Backspace deletions via the customized Action Bottom Row without touching the mouse.' },
        ],
        exampleBefore: 'The patient presents with um mild abdominal pain radiating to the back started about two days ago no nausea no vomiting heartbeat is regular.',
        exampleAfter: 'The patient presents with mild abdominal pain radiating to the back. Onset was approximately two days ago. Patient denies nausea and vomiting. Heart rate is regular.',
        targetAudience: ['Physicians', 'Nurses', 'Therapists', 'Veterinarians', 'Private Practices'],
        faqItems: [
            { question: 'Is Zavi HIPAA compliant?', answer: 'Zavi operates with strict No-Data-Retention policies. Enterprise implementations can be localized to completely sandbox the Gemini engine to your custom BAA cloud environment.' },
            { question: 'Can I use this on iPad Mini rounds?', answer: 'Yes! Zavi functions as a system-wide custom keyboard on iOS and Android tablet architectures.' },
        ],
        relatedUseCases: ['legal', 'email', 'accessibility'],
    },
    {
        slug: 'legal',
        title: 'Voice Typing for Legal Teams',
        metaTitle: 'Legal Dictation Software — Fast Legal Transcription | Zavi AI',
        metaDescription: 'Draft complex contracts, send rapid partner emails, and log billable hours via seamless, private cross-platform voice transcription.',
        heroTitle: 'Draft Briefs & Log Hours by Voice',
        heroSubtitle: 'Move faster than opposing counsel. Dictate complex legal documents with perfect syntax, formatting, and absolute privacy.',
        icon: '⚖️',
        problem: 'Lawyers are paralyzed by the compounding hours of drafting briefs, answering associate emails, and logging tiny increments of billable time into clunky practice management software.',
        solution: 'Zavi AI operates seamlessly inside Clio, LexisNexis, Word, and Outlook. Speak out multi-page legal arguments, while Zavi handles the punctuation, Latin phrasing, and complex structural formatting via the "Professional" tone engine.',
        howItWorks: [
            'Load up your legal brief document in Microsoft Word.',
            'Set Zavi\'s Tone selector to "Professional (Briefcase)".',
            'Dictate your arguments; Zavi immediately corrects "ums", hesitations, and disjointed logic.',
            'Use the Voice Agent (Pro) to say: "Log a 15-minute billable task in Notion for the Smith Case."',
        ],
        benefits: [
            { title: 'The "Professional" Tone Engine', description: 'Automatically forces the AI to output highly formal, stiff, perfectly structured syntax suitable for legal briefs and court filings.' },
            { title: 'Voice Agent OS (Pro)', description: 'Utilize deep API connections to draft documents in Google Docs or organize items in Notion purely through conversational commands.' },
            { title: 'Absolute Confidentiality', description: 'Attorney-client privilege is preserved via Zavi\'s no-retention streaming framework. The audio is instantly destroyed upon text injection.' },
            { title: 'Multi-Ring Mic Feedback', description: 'Animated visual indicators confirm the exact pipeline state (listening, connecting, recording) so you never miss a recorded thought.' },
        ],
        exampleBefore: '[Reviewing evidence] "Uh, state that the plaintiff clearly violated section 4 by, um, failing to deliver the documents on time as stipulated in the contract."',
        exampleAfter: 'The plaintiff committed a clear violation of Section 4 by failing to deliver the stipulated documents within the agreed-upon timeframe outlined in the contract.',
        targetAudience: ['Attorneys', 'Paralegals', 'Legal Assistants', 'Consultants'],
        faqItems: [
            { question: 'Can it understand Latin legal phrases?', answer: 'Yes, the underlying Gemini/Claude LLM models are heavily trained on legal corpi. Further accuracy can be achieved by injecting terms into the Zavi Custom Dictionary.' },
            { question: 'Does it run standalone on Mac?', answer: 'Yes, Zavi acts as a localized desktop widget on macOS and Windows, enabling voice injection into any native app without copy-pasting.' },
        ],
        relatedUseCases: ['medical', 'sales', 'slack'],
    },
    {
        slug: 'engineers',
        title: 'Voice Typing for Engineers',
        metaTitle: 'Voice Input for Software Engineers — Code & Communicate | Zavi AI',
        metaDescription: 'Execute GitHub workflows, write Jira tickets, and dictate architectural design docs 4x faster using Zavi AI Developer integrations.',
        heroTitle: 'Code is Fast. Documentation is Slow.',
        heroSubtitle: 'Stop context-switching. Update Jira tickets, merge PRs, and draft technical specs purely via Voice Agent.',
        icon: '💻',
        problem: 'Engineers despise writing documentation or updating Jira. The physical act of moving hands off the IDE shortcuts to type out a 300-word PR description breaks flow-state and ruins productivity.',
        solution: 'Zavi acts as your personal Junior Dev Assistant. Dictate complex technical architecture into Confluence at 150 WPM. With Zavi Pro, leverage the GitHub integration to execute workflow commands hands-free.',
        howItWorks: [
            'Finish writing a complex module inside VSCode.',
            'Tap the Voice Agent (Pro): "Create a new pull request on GitHub for the auth-refactor branch and summarize the JWT changes."',
            'Zavi triggers the OAuth pipeline, reads the branch context, and executes the PR.',
            'You never took your hands off the keyboard.',
        ],
        benefits: [
            { title: 'GitHub Integration (Pro)', description: 'Securely link your GitHub account. Issue Voice Agent commands to create PRs, summarize diffs, assign reviewers, or check CI/CD status.' },
            { title: 'BYOK (Bring Your Own Key)', description: 'Plug in your own OpenAI `gpt-4o` or Anthropic `claude-3-5-sonnet` API keys to supercharge the backend reasoning capabilities for complex coding workflows.' },
            { title: 'Developer Dictionary', description: 'Add your custom microservice names (e.g. `auth-worker-v2`) and tech-stack terminology into the local dictionary for perfect speech recognition.' },
            { title: 'Haptic Feedback Transitions', description: 'Contextual haptics and TTS chimes let you know exactly when a multi-turn Voice Agent sequence has completed in the background.' },
        ],
        exampleBefore: 'Voice Agent: "Check if the frontend tests passed on my latest UI branch."',
        exampleAfter: '[TTS Output] "The GitHub Actions CI/CD pipeline for branch ui-refactor completed successfully 3 minutes ago."',
        targetAudience: ['Software Engineers', 'DevOps', 'Product Managers', 'CTOs'],
        faqItems: [
            { question: 'Does Zavi inject actual code?', answer: 'Zavi is optimized for natural language compilation (documentation, Slack, emails), but you can trigger the Magic Wand "Rewrite as Python code" to generate boilerplate structures inside your IDE.' },
            { question: 'Is my employer\'s source code safe?', answer: 'Yes. Zavi only accesses GitHub data explicitly requested by the Voice Agent during a specific multi-turn tool call, and no data is retained or utilized for model training.' },
        ],
        relatedUseCases: ['product', 'slack', 'accessibility'],
    },
    {
        slug: 'product',
        title: 'Voice Typing for Product Managers',
        metaTitle: 'Product Manager AI Voice Assistant — Write PRDs Faster | Zavi AI',
        metaDescription: 'Draft PRDs, sprint scopes, and Jira updates instantly. Connect your product stack via Voice Agent to eliminate tedious PM data entry.',
        heroTitle: 'Ship Features, Not PRDs',
        heroSubtitle: 'Dictate complex Product Requirement Docs at the speed of thought. Let Zavi extract the tickets and update your roadmap via Voice Agent.',
        icon: '🚀',
        problem: 'Product Managers spend hours translating stakeholder meetings into comprehensive Product Requirement Documents (PRDs) and constantly updating Jira tickets, taking them away from actual product strategy.',
        solution: 'Zavi operates as your Chief of Staff. Dictate your raw feature ideas at 150 WPM directly into Notion. Use the Zavi Voice Agent to automatically transform those notes into perfectly formatted Jira Epics.',
        howItWorks: [
            'Just finished a user interview? Hit the Zavi mic.',
            'Dictate the entire 20-minute conversation recap into your Notes app.',
            'Tap the Magic Wand and say: "Rewrite this as 3 actionable user stories".',
            'Zavi outputs the perfectly formatted Agile framework directly into your document.',
        ],
        benefits: [
            { title: 'Magic Wand Formatting', description: 'Convert stream-of-consciousness meeting rambles into strict PRD templates, complete with acceptance criteria, using the Magic Wand.' },
            { title: 'Connected Jira (Pro)', description: 'Link your workspace. Say "Update the navigation ticket to blocked," and Zavi handles the API call seamlessly.' },
            { title: 'Flow Session Multitasking', description: 'The mic stays active in the background for 5 minutes. Jump between Slack, Jira, and Figma while maintaining a continuous voice dictation stream.' },
            { title: 'Custom "Agile" Snippets', description: 'Pre-load your company\'s specific feature template. Say "Insert feature snippet" to instantly populate the document structure.' },
        ],
        exampleBefore: 'Voice Agent: "Create a Jira ticket assigned to David to fix the navigation bar padding in the staging environment."',
        exampleAfter: '[TTS Output] "The Jira task ENG-104 has been created and assigned to David with your requested details."',
        targetAudience: ['Product Managers', 'Scrum Masters', 'Agile Coaches', 'Founders'],
        faqItems: [
            { question: 'Does it work inside Figma?', answer: 'Yes! Zavi replaces the system keyboard natively on desktop and mobile, so it inputs text perfectly into Figma comment threads and design specs.' },
            { question: 'Can I change the AI model?', answer: 'Yes, Zavi users can supply their own OpenAI or Anthropic API keys for specialized reasoning tasks within the workspace.' },
        ],
        relatedUseCases: ['engineers', 'sales', 'slack'],
    },
    {
        slug: 'therapists',
        title: 'Voice Typing for Therapists & Counseling',
        metaTitle: 'Private Voice Dictation for Therapists — HIPAA Compliant | Zavi AI',
        metaDescription: 'Dictate session notes quickly and privately. Zavi AI strictly deletes all audio instantly, perfect for sensitive counseling documentation.',
        heroTitle: 'Session Notes, Solved',
        heroSubtitle: 'Spend more time with clients and less time staring at a screen. Dictate highly sensitive psychiatric and counseling notes securely.',
        icon: '🛋️',
        problem: 'Therapists and psychologists suffer from immense administrative overhead, spending late evenings typing up detailed clinical session notes while attempting to maintain perfect client confidentiality.',
        solution: 'Zavi provides a localized, zero-retention dictation layer. Speak your session notes directly into your secure practice management software. Zavi processes the stream instantly and securely erases the data from its processing RAM.',
        howItWorks: [
            'After a client session, open your secure EMR system.',
            'Trigger Zavi dictation via your desktop hotkey.',
            'Speak the clinical summary at 150 WPM.',
            'The AI removes stutters and "ums", formatting the text cleanly into your interface.',
        ],
        benefits: [
            { title: 'Zero Data Retention', description: 'Client privacy is paramount. Zavi\'s cloud architecture destroys the audio payload immediately after text generation. Data is never mined.' },
            { title: 'Tone Selection', description: 'Select the "Professional" tone to ensure clinical notes maintain a formalized, objective, and legally sound structure.' },
            { title: 'Live Transcribe Limits', description: 'Unlike typical mobile keyboards that cut off after 60 seconds, Zavi allows infinite, continuous dictation for marathon documentation sessions.' },
            { title: 'No Learning Curve', description: 'There is no acoustic voice training required. Zavi instantly understands your accent and natural speaking rhythm.' },
        ],
        exampleBefore: 'Client discussed um increased anxiety regarding the upcoming move and we talked about uh coping strategies for the transition.',
        exampleAfter: 'The client expressed increased anxiety regarding their upcoming relocation. The session focused on developing actionable coping strategies for the transition period.',
        targetAudience: ['Psychologists', 'LCSWs', 'Marriage Counselors', 'Psychiatrists'],
        faqItems: [
            { question: 'Is the data used to train the AI?', answer: 'Absolutely not. We have a strict zero-training policy for both our proprietary and partner LLM models on user dictation inputs.' },
            { question: 'Does it work with SimplePractice?', answer: 'Yes, Zavi operates as a localized system input natively on Windows and Mac, bridging perfectly into web-based applications like SimplePractice.' },
        ],
        relatedUseCases: ['medical', 'accessibility', 'writers'],
    },
    {
        slug: 'hr-recruiting',
        title: 'Voice Typing for HR & Recruiters',
        metaTitle: 'Voice Typing for Recruiters — Streamline Candidate Outreach | Zavi AI',
        metaDescription: 'Draft LinkedIn InMails 4x faster, log interview feedback instantly, and automate your hiring pipeline with Zavi Voice Agent.',
        heroTitle: 'Hire Top Talent, Faster',
        heroSubtitle: 'Dictate interview feedback into your ATS while walking. Use the Voice Agent to send personalized LinkedIn outreach totally hands-free.',
        icon: '🤝',
        problem: 'Recruiters are bogged down by repetitive LinkedIn messaging, typing up post-interview scorecard feedback, and navigating complex Applicant Tracking Systems (ATS).',
        solution: 'Zavi accelerates the entire hiring lifecycle. Dictate deeply personalized connection requests on LinkedIn at the speed of thought, and rely on the AI to fix grammar. Post-interview, capture your immediate impressions via voice before you forget them.',
        howItWorks: [
            'Just finished a candidate screen?',
            'Open Greenhouse or Lever on your phone.',
            'Tap the Zavi mic and speak your entire unfiltered impression.',
            'Zavi outputs a clean, grammatically perfect summary into the scorecard field.',
        ],
        benefits: [
            { title: 'LinkedIn Integration (Pro)', description: 'Use the Voice Agent to state: "Find Sarah Connor on LinkedIn and send an InMail asking if she\'s open to Lead Engineering roles." Zavi executes this instantly.' },
            { title: 'The Custom Dictionary', description: 'Never misspell complex tech-stack requirements (e.g., "Kubernetes", "Next.js 14") when dictating job descriptions.' },
            { title: 'Cross-Device Workflow', description: 'Start sourcing on your Mac desktop app and finish logging ATS notes on your iOS device via the unified Zavi keyboard.' },
            { title: 'Magic Wand Personalization', description: 'Paste a generic job spec, highlight it, and say "Make this sound more exciting and welcoming." The LLM rewrites it instantly.' },
        ],
        exampleBefore: 'Um the candidate had good React skills but uh seemed a little weak on the backend node architecture questions.',
        exampleAfter: 'The candidate demonstrated strong proficiency in React. However, they exhibited some gaps in knowledge regarding backend Node.js architecture.',
        targetAudience: ['Technical Recruiters', 'HR Generalists', 'Headhunters', 'Hiring Managers'],
        faqItems: [
            { question: 'Does it work with LinkedIn Recruiter?', answer: 'Yes, because Zavi acts as your localized system keyboard, it functions flawlessly inside LinkedIn Recruiter\'s messaging center.' },
            { question: 'Can I translate messages to offshore candidates?', answer: 'Yes! Select the Live Translation toggle, speak in English, and instantly output perfect Spanish or French.' },
        ],
        relatedUseCases: ['sales', 'email', 'slack'],
    },
    {
        slug: 'real-estate',
        title: 'Voice Typing for Real Estate',
        metaTitle: 'Voice AI for Realtors — Write Listings & Follow-Ups Fast | Zavi AI',
        metaDescription: 'Write property listings instantly while walking the house. Automate CRM follow-ups while driving between showings.',
        heroTitle: 'Close More Houses. Type Less.',
        heroSubtitle: 'Generate beautiful MLS listings via voice and send client follow-ups instantly from your car.',
        icon: '🏠',
        problem: 'Real Estate Agents are constantly on the move. Typing detailed property descriptions and fighting with mobile CRM interfaces while driving between showings destroys productivity and delays critical client responses.',
        solution: 'Zavi turns your smartphone into a mobile command center. Walk through a new listing and dictate the features aloud. The AI generates a perfect, compelling MLS description. Follow up with buyers via voice while maintaining constant momentum.',
        howItWorks: [
            'Walking through a new 3-bedroom property?',
            'Open your notes app and trigger Zavi.',
            'Describe what you see: "Hardwood floors, vaulted ceilings, um, stainless steel appliances."',
            'Tap the Magic Wand and say: "Rewrite this as an exciting MLS property listing in paragraph form."',
        ],
        benefits: [
            { title: 'Write Listings Quicker', description: 'Bypass writer\'s block entirely. Just speak the raw facts of the property, and let Zavi\'s Magic Wand construct the marketing copy.' },
            { title: 'Drive & Dictate (Voice Agent)', description: 'Use the Voice Agent while driving to say: "Email the Smith family the closing documents." Zavi interfaces with Gmail securely.' },
            { title: 'Emojis for Marketing', description: 'Enable the Emoji Toggle when drafting Instagram posts or WhatsApp broadcasts for open houses to automatically inject engaging 🏡 ✨ icons.' },
            { title: 'Offline-Ready Architecture', description: 'If you lose signal in a rural property, Zavi\'s Darwin IPC architecture ensures your audio state won\'t crash when the connection drops.' },
        ],
        exampleBefore: '[Magic Wand command]: "Rewrite this bulleted list of house features into a compelling Zillow listing."',
        exampleAfter: 'Welcome to your dream home! 🏡 This stunning property features gorgeous vaulted ceilings that flood the space with natural light. The chef\'s kitchen is fully equipped with modern stainless steel appliances... ✨',
        targetAudience: ['Realtors', 'Brokers', 'Property Managers', 'Real Estate Investors'],
        faqItems: [
            { question: 'Can I use Zavi on my iPhone?', answer: 'Yes, Zavi operates as a native custom iOS keyboard, meaning it is accessible in iMessage, Safari, and your proprietary MLS mobile app.' },
            { question: 'Does the voice recognition understand neighborhood names?', answer: 'Out of the box, Zavi is highly localized. For extremely obscure local subdivisions, simply add the phrase to your Zavi Custom Dictionary for perfect spelling.' },
        ],
        relatedUseCases: ['sales', 'writers', 'whatsapp'],
    },
    {
        slug: 'translators',
        title: 'Live Voice Translation',
        metaTitle: 'Real-Time Voice Translation Keyboard | Speak Hindi, Type English',
        metaDescription: 'Speak in your native language and type perfectly in 15+ global languages instantly. The ultimate multilingual communication tool.',
        heroTitle: 'Speak Local. Type Global.',
        heroSubtitle: 'Break the language barrier. Speak in Hindi, Arabic, or Spanish, and let Zavi instantly type perfectly formatted English.',
        icon: '🌍',
        problem: 'Bilingual professionals and distributed global teams struggle with context-switching between native languages and professional English. Constantly copying and pasting from Google Translate is tedious and disrupts the flow of conversation.',
        solution: 'Zavi builds a real-time translator directly into your system keyboard. Tap the Translate toggle, speak in your native tongue, and Zavi executes a neural-net translation, inputting grammatically perfect English (or 15 other targets) directly into your active window.',
        howItWorks: [
            'Open a Slack thread with your US-based team.',
            'Tap the Translate icon on your Zavi keyboard.',
            'Speak your technical update comfortably in Hindi or German.',
            'Zavi processes the audio and types a formal, native-sounding English update instantly.',
        ],
        benefits: [
            { title: '15+ Target Languages', description: 'Translate seamlessly into English, German, French, Spanish, Hindi, Chinese, Arabic, Japanese, Portuguese, Korean, Italian, Russian, Dutch, Turkish, or Vietnamese.' },
            { title: 'Context-Aware Translation', description: 'Unlike raw literal translators, Zavi utilizes LLM reasoning to ensure idioms and industry jargon are translated into natural-sounding target concepts.' },
            { title: 'Zero App Switching', description: 'Never open a separate translation app again. Zavi operates locally underneath WhatsApp, WeChat, or Outlook.' },
            { title: 'Tone Nuance', description: 'Combine translation with Tone controls. Speak a casual Spanish sentence, and output a highly formal English email.' },
        ],
        exampleBefore: '[Speaking in Hindi]: "मुझे लगता है कि हमें कल सुबह कोड डिप्लॉय करना चाहिए।"',
        exampleAfter: '[Output in English]: "I believe we should deploy the code tomorrow morning."',
        targetAudience: ['Distributed Teams', 'Offshore Contractors', 'ESL Professionals', 'Digital Nomads'],
        faqItems: [
            { question: 'Does it support regional dialects?', answer: 'Yes, Zavi\'s advanced acoustic model supports regional accents (e.g., UK English vs Indian English) seamlessly without requiring manual configuration.' },
            { question: 'Is the translation feature free?', answer: 'Yes! The Live Translation toggle is included in the Free tier, subject to the daily 1,000-word limit. Pro users get unlimited translation.' },
        ],
        relatedUseCases: ['whatsapp', 'slack', 'email'],
    },
    {
        slug: 'executives',
        title: 'Voice AI for Executives & Founders',
        metaTitle: 'Executive AI Voice Assistant — Manage Email 4x Faster | Zavi AI',
        metaDescription: 'Clear your inbox, direct your team, and draft memos instantly. Zavi is the ultimate AI workflow multiplier for busy founders and executives.',
        heroTitle: 'Execute at the Speed of Thought',
        heroSubtitle: 'Tackle a flooded inbox, draft investor updates, and assign tasks to your team purely by talking.',
        icon: '🕴️',
        problem: 'Founders and C-Suite executives are the ultimate bottleneck for their companies. High-velocity decision-making is slowed down by the physical limitation of typing out emails, memos, and Slack updates.',
        solution: 'Zavi acts as a digital Chief of Staff. Dictate a 3-paragraph investor update in 60 seconds. Use the Voice Agent to instantly route action items to your direct reports across Slack and Gmail while walking to your next meeting.',
        howItWorks: [
            'Walking between conference rooms?',
            'Tap the Zavi Voice Agent on your smartwatch or phone.',
            'Say: "Slack the Executive channel that the Q3 board presentation needs a budget revision by 5 PM."',
            'Zavi executes the OAuth command seamlessly.'
        ],
        benefits: [
            { title: 'Executive Voice Agent (Pro)', description: 'Delegate tasks instantly. Voice command Zavi to schedule meetings on Google Calendar or pull files from Google Drive.' },
            { title: 'Polished "Professional" Tone', description: 'Ensure you never send a rushed, typo-ridden message. Zavi\'s Professional tone ensures executive-level communication formatting.' },
            { title: 'Magic Wand Rewrites', description: 'Paste a draft from an associate. Highlight it and say "Make this sound more authoritative and concise." Zavi rewrites it in seconds.' },
            { title: 'End-to-End Encryption', description: 'Corporate data remains secure. We utilize SOC-2 compliant infrastructure, and custom Bring-Your-Own-Key (BYOK) architecture is available.' },
        ],
        exampleBefore: 'Voice Agent: "Email the board of directors the Q3 financial report from my Google Drive and tell them we beat targets by 14%."',
        exampleAfter: '[TTS Chime] "The email has been sent to the Board with the Q3 Financial Report PDF attached."',
        targetAudience: ['CEOs', 'Startup Founders', 'VPs', 'Directors'],
        faqItems: [
            { question: 'Can Zavi manage my calendar?', answer: 'Yes, with the Pro tier, you can link your Google Workspace. The Voice Agent can create, summarize, and modify calendar events.' },
            { question: 'Can I dictate on an airplane?', answer: 'Zavi requires an internet connection to route to the Gemini LLM for grammar correction, so airplane use requires onboard Wi-Fi.' },
        ],
        relatedUseCases: ['email', 'slack', 'product'],
    },
    {
        slug: 'marketers',
        title: 'Voice AI for Marketers & Creators',
        metaTitle: 'AI Writing Assistant for Marketers — Fast Copywriting | Zavi AI',
        metaDescription: 'Draft newsletters, social media posts, and ad copy 4x faster. Use the Magic Wand to instantly change the tone of your marketing copy.',
        heroTitle: 'Scale Your Content Pipeline',
        heroSubtitle: 'Draft blogs, ad copy, and newsletters instantly. Change the tone to "Witty" and add targeted emojis with a single tap.',
        icon: '🎯',
        problem: 'Content marketers are under pressure to constantly produce high-volume, engaging copy across multiple platforms (LinkedIn, Twitter, Newsletters, Blogs) without sacrificing brand voice.',
        solution: 'Zavi provides an infinite creative pipeline. Dictate a single raw thought into your word processor at 150 WPM. Copy that paragraph, jump to Twitter, and use the Zavi Magic Wand to say: "Rewrite this as a viral, witty Twitter thread."',
        howItWorks: [
            'Dictate a raw 500-word product announcement into Google Docs.',
            'Switch to the Twitter/X app. Paste the text.',
            'Tap the Magic Wand and state: "Condense this into an exciting tweet.".',
            'Zavi injects the perfect, character-limited copy.',
        ],
        benefits: [
            { title: 'Multi-Tone Copywriting', description: 'Switch between "Professional" for LinkedIn posts, "Casual" for newsletters, and "Witty" for Twitter with a single physical toggle.' },
            { title: 'Automated Emojis', description: 'Enable the Emoji Toggle to allow the AI to automatically analyze semantic intent and inject high-converting emojis into your social snippets.' },
            { title: 'Built-in Web Search', description: 'Need a stat for your blog post? Ask the Voice Agent: "What is the current global market cap for AI?" Zavi runs a real-time Tavily search.' },
            { title: 'Historical Iterations', description: 'Don\'t like the rewrite? Delete it, open the Zavi History panel, and restore your previous vocal draft instantly.' },
        ],
        exampleBefore: '[Magic Wand Directive]: "Rewrite this boring feature list into an exciting Instagram caption targeting Gen-Z."',
        exampleAfter: 'Stop stressing over data entry! 🛑 Zavi just dropped the ultimate workflow hack. ⚡ Drop a 🔥 below if you\'re ready to work smarter, not harder.',
        targetAudience: ['Social Media Managers', 'Copywriters', 'Growth Marketers', 'Founders'],
        faqItems: [
            { question: 'Does the Emoji toggle work in all apps?', answer: 'Yes, the Emoji integration operates universally. It analyzes the context of your speech and injects UTF-8 emojis directly into the text field.' },
            { question: 'Can I set a custom brand voice?', answer: 'In addition to our 4 built-in tones, power users can utilize the BYOK (Bring Your Own Key) feature to inject a custom system prompt into an Anthropic model.' },
        ],
        relatedUseCases: ['writers', 'whatsapp', 'email'],
    },
    {
        slug: 'customer-support',
        title: 'Voice Typing for Customer Support',
        metaTitle: 'Voice AI for Customer Support — Clear Tickets Faster | Zavi AI',
        metaDescription: 'Clear Zendesk and Intercom tickets 4x faster. Speak empathetic, structurally perfect responses to angry customers instantly.',
        heroTitle: 'Clear the Ticket Queue, Fast',
        heroSubtitle: 'Respond to Zendesk and Intercom tickets with deep, empathetic, grammatically perfect responses—just by talking.',
        icon: '🎧',
        problem: 'Customer Support representatives face massive daily ticket queues. Typing out empathetic, detailed solutions to frustrated customers takes immense physical effort and risks accidental typos that degrade brand trust.',
        solution: 'Zavi AI allows agents to tackle complex tickets conversationally. Speak the raw technical solution, and select the "Professional" tone. Zavi will instantly generate a warm, grammatically perfect troubleshooting guide for the customer.',
        howItWorks: [
            'Open a difficult ticket in Zendesk, Intercom, or Front.',
            'Tap the Zavi mic to trigger the dictation panel.',
            'Speak the core technical fix: "Tell the user to clear their cache and restart the router."',
            'Zavi outputs: "Hi there! To resolve this issue, please kindly clear your browser cache and perform a quick router restart. Let me know if that helps!"',
        ],
        benefits: [
            { title: 'The "Casual / Smile" Tone', description: 'Frustrated customers require empathy. The Casual tone automatically rewords robotic technical instructions into warm, human-centric guidance.' },
            { title: 'Custom Snippet Macros', description: 'Integrate your company\'s most complex URLs or troubleshooting blocks directly into Zavi. Say "refund policy snippet" to inject 3 paragraphs instantly.' },
            { title: 'Multilingual Support', description: 'A ticket comes in from Germany? Tap the Live Translation icon, speak your English response, and input flawless German directly into Zendesk.' },
            { title: 'Hold-to-Repeat Deletions', description: 'Custom action buttons allow support reps to rapidly highlight and delete massive text blocks without lifting their fingers from the home row.' },
        ],
        exampleBefore: 'Tell the user we cant do a refund because it\'s past 30 days but we can offer a 20 percent discount on the next order.',
        exampleAfter: 'I completely understand your frustration. While we are unable to process a full refund as the 30-day window has passed, I would love to offer you a 20% discount on your next order as a courtesy.',
        targetAudience: ['Customer Success Managers', 'Support Agents', 'Account Managers'],
        faqItems: [
            { question: 'Does Zavi integrate with Zendesk?', answer: 'Yes! Zavi functions as a system-wide OS input tool across Mac and Windows, meaning it operates natively inside Chrome, Safari, and any web-based ticketing system.' },
            { question: 'Can we deploy this to our entire team?', answer: 'Absolutely. Please contact our Enterprise sales team to discuss volume licensing for large customer support centers.' },
        ],
        relatedUseCases: ['sales', 'slack', 'email'],
    },
    {
        slug: 'podcasters',
        title: 'Voice Typing for Podcasters & Audio',
        metaTitle: 'Voice AI for Podcasters — Generate Show Notes | Zavi AI',
        metaDescription: 'Draft YouTube descriptions and podcast show notes instantly via voice. Utilize real-time transcription to outline your creative ideas.',
        heroTitle: 'Outline Your Episodes Aloud',
        heroSubtitle: 'Draft your show notes, YouTube descriptions, and interview questions entirely by speaking to your workstation.',
        icon: '🎙️',
        problem: 'Audio creators thrive on the mic but get bogged down when forced to type out detailed show notes, timestamps, YouTube descriptions, and guest outreach emails.',
        solution: 'Zavi keeps you in your element. Never turn off the mic. Dictate your entire episode summary into a Google Doc, and let the AI perfectly format the capitalization and grammar. Highlight sections to instantly reformat them using the Magic Wand.',
        howItWorks: [
            'Finish rendering your latest audio episode.',
            'Open your CMS or YouTube upload dashboard.',
            'Tap Zavi and dictate an enthusiastic summary of the episode topics.',
            'Use the Magic Wand: "Turn this paragraph into a numbered list of topics for my audience."',
        ],
        benefits: [
            { title: 'Infinite Dictation Sessions', description: 'Outline a massive 3-hour episode structure without the dictation timing out. Zavi\'s background architecture stays active endlessly.' },
            { title: 'Magic Wand Repurposing', description: 'Highlight your show notes. Say: "Condense this into a 280-character Twitter teaser." Post it instantly to drive engagement.' },
            { title: 'The Witty Tone Engine', description: 'Ensure your YouTube descriptions don\'t sound like robotic corporate text. The Witty tone ensures your copy matches the energy of your show.' },
            { title: 'Custom Dictionary', description: 'Train Zavi to understand your highly specific podcast terminology, guest names, or niche industry jargon.' },
        ],
        exampleBefore: '[Magic Wand command]: "Turn my scattered episode outline into a professional introductory paragraph for YouTube."',
        exampleAfter: 'Welcome back to another exciting episode! Today, we dive deep into the fascinating world of AI robotics, discussing the latest breakthroughs and what they mean for the future of the workforce.',
        targetAudience: ['Podcasters', 'YouTubers', 'Streamers', 'Audio Engineers'],
        faqItems: [
            { question: 'Does Zavi transcribe existing audio files?', answer: 'Currently, Zavi is optimized for real-time live dictation and OS control via the Voice Agent. It is an active input tool, not a batch transcriber.' },
            { question: 'What microphone should I use?', answer: 'Zavi interfaces natively with the system\'s active CoreAudio pipeline. Whether you are using internal AirPods or a $500 Shure SM7B XLR rig, Zavi captures the stream beautifully.' },
        ],
        relatedUseCases: ['writers', 'marketers', 'slack'],
    },
    {
        slug: 'teachers',
        title: 'Voice Typing for Teachers & Educators',
        metaTitle: 'Voice AI for Teachers — Fast Grading & Lesson Plans | Zavi AI',
        metaDescription: 'Leave detailed student feedback 5x faster via voice. Dictate lesson plans instantly using Zavi AI\'s native OS keyboard.',
        heroTitle: 'Grade Papers, Not Your Patience',
        heroSubtitle: 'Leave incredibly detailed, empathetic feedback on student assignments in seconds. Dictate your entire week\'s lesson plans by talking.',
        icon: '🍎',
        problem: 'Educators are drowning in administrative overhead. Typing out personalized, constructive feedback for 100+ students on a Saturday morning is a fast track to teacher burnout.',
        solution: 'Zavi gives educators their weekends back. Open Google Classroom or Canvas, tap the Zavi mic, and speak your feedback fluidly. The AI structures it, fixes your grammar, and types it directly into the grading portal.',
        howItWorks: [
            'Review a student\'s essay in Canvas.',
            'Tap your Zavi hotkey to open the mic.',
            'Speak naturally: "Great thesis, but the third paragraph needs more historical context. Keep up the good work!"',
            'Zavi outputs the perfectly formatted, encouraging feedback instantly.',
        ],
        benefits: [
            { title: 'The "Smile/Casual" Tone', description: 'Ensure your feedback never reads as overly harsh. Select the Casual Tone to automatically inject warmth and encouragement into your dictation.' },
            { title: 'Magic Wand Lesson Plans', description: 'Dictate a raw list of topics you want to cover. Highlight it and say: "Turn this into a structured 45-minute lesson plan for 8th graders."' },
            { title: 'Custom Snippets', description: 'Create Voice Macros for common grading rubrics. Say "Insert plagiarism warning" to drop a pre-written 3-paragraph policy instantly.' },
            { title: 'Multilingual Parent Communication', description: 'Need to email a non-English speaking parent? Use Live Translation. Speak in English, and output perfect Spanish or Mandarin directly into Gmail.' },
        ],
        exampleBefore: 'Voice translation: "Your son is doing great in math but needs to focus more during quiet reading time."',
        exampleAfter: '[Spanish Output]: "A su hijo le va muy bien en matemáticas, pero necesita concentrarse más durante el tiempo de lectura en silencio."',
        targetAudience: ['K-12 Teachers', 'University Professors', 'Tutors', 'Special Education Instructors'],
        faqItems: [
            { question: 'Does Zavi work with Google Classroom?', answer: 'Yes, Zavi behaves as a system-level keyboard on Mac and Windows, so it types natively into Chrome, Safari, and any LMS portal like Canvas or Blackboard.' },
            { question: 'Can my students use this?', answer: 'Absolutely. We offer a dedicated Students use case, and the Free tier is perfect for students writing essays or overcoming dyslexia.' },
        ],
        relatedUseCases: ['students', 'translators', 'email'],
    },
    {
        slug: 'fitness',
        title: 'Voice Typing for Personal Trainers',
        metaTitle: 'Voice AI for Fitness Coaches — Log Workouts Fast | Zavi AI',
        metaDescription: 'Update client programming instantly from the gym floor. Send voice-translated text check-ins directly into WhatsApp or TrueCoach.',
        heroTitle: 'Coach More. Type Less.',
        heroSubtitle: 'Never pull out your laptop on the gym floor again. Update client workouts and dictate WhatsApp check-ins totally hands-free.',
        icon: '🏋️',
        problem: 'Personal trainers lose hours typing up complex workout programs on small mobile keyboards and struggling to keep up with dozens of client check-in messages across WhatsApp and iMessage.',
        solution: 'Zavi turns your mobile device into a high-speed command center. Walk the gym floor and dictate sets and reps directly into TrueCoach or Trainerize. Fire off perfectly formatted WhatsApp check-ins between your own sets.',
        howItWorks: [
            'Open a client\'s program in your coaching app.',
            'Tap the Zavi mic on your iOS or Android device.',
            'Say: "Four sets of eight Romanian deadlifts at 135 pounds, superset with hanging leg raises."',
            'Zavi formats the text beautifully into the app.',
        ],
        benefits: [
            { title: 'Custom Fitness Dictionary', description: 'Train Zavi to understand highly specific exercise acronyms (e.g., "AMRAP", "RPE 8", "BFR training") so they are never autocorrected.' },
            { title: 'Emoji Automation', description: 'Fitness communication relies on energy. Enable the Emoji Toggle to let Zavi automatically add 💪 🔥 icons to your client motivation texts.' },
            { title: 'Voice Agent (Pro)', description: 'Use the Voice Agent while driving home to say: "Slack the coaching team that the morning bootcamp is moved to 8 AM tomorrow."' },
            { title: 'No Hand Strain', description: 'After gripping heavy barbells all day, your hands and forearms are exhausted. Let your voice do the heavy lifting for your admin work.' },
        ],
        exampleBefore: 'Hey man great job on the squats today um next week lets bump the weight up to 225 for your working sets.',
        exampleAfter: 'Hey man, great job on the squats today! 💪 Next week, let\'s bump the weight up to 225 lbs for your working sets. Keep up the fire! 🔥',
        targetAudience: ['Personal Trainers', 'Strength Coaches', 'Online Fitness Instructors', 'Physical Therapists'],
        faqItems: [
            { question: 'Can I use this on my phone?', answer: 'Yes, Zavi is available as a custom keyboard replacement for both iOS and Android, allowing you to use it across all your mobile apps.' },
            { question: 'Will gym background noise break the AI?', answer: 'No. Zavi uses an advanced acoustic Voice Activity Detection (VAD) model that isolates your vocal frequencies and filters out background clanking and gym music.' },
        ],
        relatedUseCases: ['whatsapp', 'marketers', 'medical'],
    },
    {
        slug: 'consultants',
        title: 'Voice AI for Consultants & Strategy',
        metaTitle: 'Voice AI for Consultants — Draft Executive Formatting | Zavi AI',
        metaDescription: 'Dictate complex strategic recommendations and use the Magic Wand to instantly reformat them into executive summaries.',
        heroTitle: 'Strategic Thinking, Scaled',
        heroSubtitle: 'Dictate complex client recommendations. Use the Magic Wand to rewrite them into razor-sharp executive summaries instantly.',
        icon: '💼',
        problem: 'Management consultants spend a disproportionate amount of time converting raw meeting notes and strategic hypotheses into highly polished, perfectly formatted deliverables for C-suite clients.',
        solution: 'Zavi bridges the gap between raw thought and polished deliverable. Dictate your entire strategic thesis into a slide deck or Word document. Use the Magic Wand to condense your rambling into a hard-hitting executive summary.',
        howItWorks: [
            'Just left a grueling 3-hour client workshop?',
            'Dictate the entire brain dump into your notes app.',
            'Highlight the text. Tap the Magic Wand.',
            'Command: "Rewrite this as a 3-bullet executive summary focusing on cost reduction."',
        ],
        benefits: [
            { title: 'The Professional Tone', description: 'Never accidentally send a casual Slack message to a Fortune 500 client. The Professional tone engine ensures all output is formally structured and devoid of slang.' },
            { title: 'Live Translation for Global Clients', description: 'Running a project in Germany but you speak English? Use the Live Translator to dictate your emails and Slack updates directly into flawless German.' },
            { title: 'Connected Google Drive (Pro)', description: 'Use the Voice Agent to instantly pull context: "Summarize the Q1 Financials PDF in my Google Drive and email the bullet points to the engagement manager."' },
            { title: 'Offline-Ready IPC', description: 'Working on a secure, air-gapped client site? Zavi\'s core architecture ensures your clipboard and text routing never crash, even on restrictive corporate Wi-Fi.' },
        ],
        exampleBefore: '[Magic Wand Directive]: "Rewrite this page of meeting notes into a formal project update email to the client CEO."',
        exampleAfter: '[Output]: "Dear Management Team, Please find below the executive summary regarding Phase 1 of the restructuring initiative, highlighting three key areas for immediate cost reduction..."',
        targetAudience: ['Management Consultants', 'Strategy Analysts', 'Freelance Experts', 'Agency Owners'],
        faqItems: [
            { question: 'Can I use my proprietary consulting frameworks?', answer: 'Yes, use the Custom Snippets feature to build voice-activated macros for your firm\'s specific MECE frameworks or SWOT analysis templates.' },
            { question: 'Is client confidentiality protected?', answer: 'Absolutely. Zavi operates a strict Privacy-First Architecture utilizing zero-data-retention APIs. Audio payloads are destroyed immediately post-transcription.' },
        ],
        relatedUseCases: ['executives', 'sales', 'email'],
    },
    {
        slug: 'drivers',
        title: 'Voice Typing for Drivers & Logistics',
        metaTitle: 'Hands-Free Voice AI for Drivers — Stay Safe on the Road | Zavi AI',
        metaDescription: 'Send perfectly formatted fleet updates, CRM logs, and translated messages entirely hands-free while driving.',
        heroTitle: 'Eyes on the Road. Work Done.',
        heroSubtitle: 'The ultimate hands-free dictation tool for logistics professionals, delivery drivers, and field service technicians.',
        icon: '🚚',
        problem: 'Commercial drivers and field technicians constantly need to update dispatch, log CRM notes, or text clients, but attempting to type on a mobile device while operating a vehicle is dangerous and illegal.',
        solution: 'Zavi provides a massive safety upgrade. Drivers can use the Voice Agent to route complex messages to dispatch via Slack or text clients via WhatsApp, completely hands-free and with perfect, AI-corrected grammar.',
        howItWorks: [
            'Driving the route and hit unexpected traffic?',
            'Trigger the Zavi Voice Agent via your Bluetooth headset.',
            'Say: "Slack the Dispatch channel that route 4 is delayed by 30 minutes due to construction."',
            'Zavi handles the OAuth authentication and posts the message securely.',
        ],
        benefits: [
            { title: 'Total Hands-Free Operation', description: 'With the Pro Voice Agent, you never need to touch the screen. Just speak the destination app and the message payload.' },
            { title: 'Multilingual Dispatch', description: 'Use Live Translation to speak your native language while driving, and have Zavi automatically translate and send the text in English to your centralized dispatcher.' },
            { title: 'Background Flow Sessions', description: 'Keep the dictation active in the background for up to 5 minutes so you don\'t have to keep re-triggering the mic while navigating complex intersections.' },
            { title: 'Bluetooth Audio Routing', description: 'Zavi natively hooks into your vehicle\'s Bluetooth or headset microphone, guaranteeing crystal clear audio capture despite cabin noise.' },
        ],
        exampleBefore: 'Voice Agent: "Text the customer John Smith that his delivery is 5 minutes away and ask for the gate code."',
        exampleAfter: '[TTS Output]: "Message sent to John Smith via SMS requesting the gate code."',
        targetAudience: ['Truck Drivers', 'Delivery Couriers', 'Field Service Techs', 'Uber/Lyft Drivers'],
        faqItems: [
            { question: 'Does it work with WhatsApp?', answer: 'Yes, the Voice Agent can be configured to interface directly with WhatsApp, iMessage, and core SMS protocols on both iOS and Android.' },
            { question: 'Does road noise affect the transcription?', answer: 'Our neural-acoustic engine is designed to filter out ambient low-frequency noise (like tire hum), focusing strictly on human vocal ranges.' },
        ],
        relatedUseCases: ['whatsapp', 'slack', 'customer-support'],
    },
    {
        slug: 'journalists',
        title: 'Voice Typing for Journalists & Media',
        metaTitle: 'Voice AI for Journalists — File Stories Faster | Zavi AI',
        metaDescription: 'Dictate breaking news, transcribe live interviews on the fly, and use the Magic Wand to perfectly format your editorial columns.',
        heroTitle: 'File the Story. First.',
        heroSubtitle: 'Dictate breaking news from the field directly into your CMS. Use the AI to perfectly format quotes and fix grammar instantly.',
        icon: '📰',
        problem: 'Journalists are under immense pressure to file stories rapidly from chaotic environments. Typing out interview notes and drafting articles on mobile devices leads to costly typos and missed deadlines.',
        solution: 'Zavi transforms your mobile device into a high-speed editorial desk. Dictate your raw observations and interview summaries at 150 WPM. The AI handles the punctuation, capitalization, and grammar, allowing you to file perfect copy instantly.',
        howItWorks: [
            'Standing outside a press conference?',
            'Open your publication\'s CMS on your tablet.',
            'Dictate your raw story structure aloud: "The mayor just announced a 20 percent budget increase for city parks, quote this is a massive win for the community end quote."',
            'Zavi formats the text beautifully, inserting the proper quotation marks dynamically.',
        ],
        benefits: [
            { title: 'Witty / Editorial Tone', description: 'Ensure your columns read naturally. Switch between the rigid Professional tone for hard news, or the Witty tone for lifestyle and opinion pieces.' },
            { title: 'Magic Wand Rewrites', description: 'Drafted an article that\'s way over the requested word count? Highlight the text and use the Magic Wand to say: "Condense this to 500 words while maintaining the key quotes."' },
            { title: 'Custom Dictionary for Names', description: 'Ensure you never misspell complex politician names or local geography by adding them to your syncable Custom Dictionary.' },
            { title: 'Tavily Web Search Integration', description: 'Need a quick fact check? Ask the Voice Agent: "When was the city hall originally constructed?" Zavi pulls the real-time answer.' },
        ],
        exampleBefore: '[Magic Wand command]: "Turn my scattered interview notes into a cohesive 3-paragraph news report."',
        exampleAfter: 'In a unexpected turn of events yesterday evening, the local council voted unanimously to redirect funding toward the downtown revitalization project, signaling a major shift in urban policy...',
        targetAudience: ['Journalists', 'Reporters', 'Bloggers', 'Editors'],
        faqItems: [
            { question: 'Can Zavi transcribe a recorded interview?', answer: 'Zavi is an active input tool designed for live dictation and OS control. You can hold it up to a speaker playing audio, but it is not designed for bulk batch-file transcription.' },
            { question: 'Is my unpublished story secure?', answer: 'Yes. Zavi does not train its models on user dictation, and the audio payloads are deleted instantly upon text generation.' },
        ],
        relatedUseCases: ['writers', 'podcasters', 'marketers'],
    },
    {
        slug: 'chefs',
        title: 'Voice Typing for Chefs & Kitchens',
        metaTitle: 'Hands-Free Voice AI for Chefs — Manage Kitchens | Zavi AI',
        metaDescription: 'Order inventory, scale recipes, and coordinate with vendors over WhatsApp entirely hands-free in a busy, messy kitchen.',
        heroTitle: 'Hands in the Dough. Eyes on the Kitchen.',
        heroSubtitle: 'Dictate inventory orders to vendors over WhatsApp and scale recipes on the fly without ever washing your hands to touch a screen.',
        icon: '🔪',
        problem: 'Professional kitchens are chaotic, wet, and messy. Chefs and line cooks need to constantly update inventory, text vendors, and adjust recipes, but touching a smartphone or iPad with messy hands is unsanitary and frustrating.',
        solution: 'Zavi allows the kitchen to operate entirely hands-free. Keep your tablet on the counter and use the Voice Agent to instantly route inventory requests to purveyors, or dictate recipe adjustments while actively cooking.',
        howItWorks: [
            'Notice you are low on fish during the dinner rush?',
            'Trigger the Zavi Voice Agent natively on your iPad.',
            'Say: "WhatsApp the seafood vendor that we need 30 pounds of Halibut by 6 AM tomorrow."',
            'Zavi executes the text order instantly while you keep plating.',
        ],
        benefits: [
            { title: 'Zero Hand Contact (Voice Agent)', description: 'Maintain strict food safety protocols. Zavi\'s OS-level Voice Agent can navigate connected apps without requiring a screen tap.' },
            { title: 'Multilingual Kitchen Staff', description: 'Manage a diverse kitchen? The Head Chef can speak English, and Zavi\'s Live Translation will instantly output perfect Spanish or French to the prep cooks\' Slack channel.' },
            { title: 'Magic Wand Recipe Scaling', description: 'Highlight a recipe document. Use the Magic Wand: "Scale these ingredient measurements up to serve 150 people." Zavi does the math instantly.' },
            { title: 'Custom Dictionary', description: 'Ensure complex culinary terms (e.g., "Mirepoix", "Sous-vide", "Beurre Blanc") are perfectly spelled in your menu drafts.' },
        ],
        exampleBefore: 'Voice Agent: "Slack the front of house channel that the duck special is eighty-sixed for the rest of the night."',
        exampleAfter: '[TTS Output]: "The message has been posted to the Front of House channel: The duck special is 86\'d for the rest of the night."',
        targetAudience: ['Executive Chefs', 'Restaurant Owners', 'Caterers', 'Food Bloggers'],
        faqItems: [
            { question: 'Will kitchen noise disrupt it?', answer: 'Zavi\'s underlying neural net is highly proficient at filtering out background clattering and fan noise to isolate human vocal commands.' },
            { question: 'Does it work with restaurant management apps?', answer: 'Yes! Zavi replaces the native mobile and desktop keyboards, allowing you to dictate directly into apps like Toast or 7shifts.' },
        ],
        relatedUseCases: ['whatsapp', 'slack', 'drivers'],
    },
    {
        slug: 'events',
        title: 'Voice Typing for Event Planners',
        metaTitle: 'Voice AI for Event Logistics — Coordinate Hands-Free | Zavi AI',
        metaDescription: 'Dictate massive logistics updates, coordinate vendors via WhatsApp, and manage event schedules entirely on the go with Zavi AI.',
        heroTitle: 'Run the Show. Drop the Keyboard.',
        heroSubtitle: 'Coordinate massive events, text vendors on the fly, and dictate complex run-of-show documents without missing a beat.',
        icon: '🎟️',
        problem: 'Event planners live entirely on their feet. Managing hundreds of moving parts, frantic vendors, and VIP clients via a tiny mobile phone keyboard during an active event is inefficient and stressful.',
        solution: 'Zavi is your digital earpiece. Draft massive, perfectly formatted client emails while walking the venue floor. Use the Voice Agent to quickly ping vendors via iMessage or WhatsApp without breaking stride or fixing typos.',
        howItWorks: [
            'Walking the floor 30 minutes before doors open?',
            'Trigger the Zavi Voice Agent.',
            'Say: "Text the AV team that the VIP microphone on stage left is dead and needs a battery swap immediately."',
            'Zavi executes the command instantly and perfectly.',
        ],
        benefits: [
            { title: 'The Casual / Excited Tone', description: 'Planning a wedding or party? Ensure your client communications don\'t sound robotic. The Casual tone injects enthusiasm into your drafted emails.' },
            { title: 'Magic Wand Formatting', description: 'Dictate a raw list of times and activities. Say: "Turn this into a perfectly structured Run-Of-Show table." Zavi formats the schedule instantly.' },
            { title: 'Background Flow Sessions', description: 'Keep the dictation active on your tablet. Give rapid-fire commands left and right to your staff while Zavi transcribes everything into an event log.' },
            { title: 'Emoji Automation', description: 'Enable the Emoji Toggle to keep your vendor and client communications light, energetic, and highly readable with smart contextual icons.' },
        ],
        exampleBefore: 'Voice Agent: "Email the catering director that we have three new gluten free guests at table 12."',
        exampleAfter: '[TTS Output]: "Email sent to the catering director: Please note we have three additional gluten-free dietary requirements at Table 12."',
        targetAudience: ['Event Planners', 'Wedding Coordinators', 'Production Managers', 'PR Agents'],
        faqItems: [
            { question: 'Will it drain my phone battery during a 12-hour event?', answer: 'Zavi leverages highly optimized OS-level APIs (like Apple\'s Speech framework for local wake words) to minimize battery drain when the mic isn\'t actively processing.' },
            { question: 'Does it work with Google Sheets?', answer: 'Yes, as a unified keyboard, Zavi can flawlessly dictate text strings into individual Google Sheets cells.' },
        ],
        relatedUseCases: ['drivers', 'hr-recruiting', 'executives'],
    },
    {
        slug: 'finance',
        title: 'Voice Typing for Finance & Accounting',
        metaTitle: 'Professional Voice AI for Finance — Draft Reports | Zavi AI',
        metaDescription: 'Dictate incredibly formal audit notes, manage client communications, and query web data via the Voice Agent with strict privacy.',
        heroTitle: 'Audit the Numbers. Automate the Text.',
        heroSubtitle: 'Draft highly formal audit reports, tax summaries, and client emails at 150 WPM using the Professional tone engine.',
        icon: '📈',
        problem: 'Financial analysts and accountants must produce highly formal, precisely worded reports and emails. Formatting rigid financial text and constantly typing complex numerical data is incredibly tedious.',
        solution: 'Zavi allows finance professionals to bypass the keyboard. Dictate your audit summaries directly into Excel or Word. Utilize the "Professional" tone to ensure the AI automatically formats your raw speech into polished corporate prose.',
        howItWorks: [
            'Reviewing a complex Q3 earnings spreadsheet?',
            'Tap the Zavi hotkey to trigger desktop dictation.',
            'Say: "The variance analysis indicates a slight dip in operating margins due to increased Q3 CAPEX, however EBITDA remains strong."',
            'Zavi cleanly inputs the hyper-correct text string into your summary document.',
        ],
        benefits: [
            { title: 'The Professional Tone', description: 'Never worry about sounding casual. Zavi\'s Professional tone strictly enforces objective, formal language suitable for SEC filings and board decks.' },
            { title: 'Number Formatting', description: 'Zavi\'s AI is trained to perfectly parse and format complex numerical strings, currencies, and percentages (e.g., "$1.43 billion", "14.5%").' },
            { title: 'Tavily Market Data Search (Pro)', description: 'Ask the Voice Agent: "What was the closing stock price for Apple yesterday?" Zavi pulls real-time financial web data instantly.' },
            { title: 'Bring Your Own API Key', description: 'For highly sensitive financial models, utilize the BYOK feature to route your text generation through your firm\'s private, enterprise-tier LLM API keys.' },
        ],
        exampleBefore: '[Magic Wand command]: "Rewrite these scattered audit notes into a formal risk assessment paragraph."',
        exampleAfter: 'Upon review of the Q2 financials, a moderate liquidity risk was identified within the accounts receivable aging schedule; however, mitigation strategies are currently being deployed.',
        targetAudience: ['Accountants (CPAs)', 'Financial Analysts', 'Investment Bankers', 'CFOs'],
        faqItems: [
            { question: 'Is my financial data secure?', answer: 'We employ a zero-data-retention architecture. Furthermore, we do not train our models on your input, making it safe for non-public financial data.' },
            { question: 'Does it understand strict financial jargon?', answer: 'Yes, the base Gemini model understands complex financial terminology, and you can further enforce specific acronyms via the Custom Dictionary.' },
        ],
        relatedUseCases: ['legal', 'executives', 'consultants'],
    },
    {
        slug: 'non-profits',
        title: 'Voice AI for Non-Profits & Fundraisers',
        metaTitle: 'Voice AI for Non-Profits — Empathetic Outreach | Zavi AI',
        metaDescription: 'Draft deeply empathetic donor emails and grant proposals 4x faster. Use the Magic Wand to perfect your narrative voice.',
        heroTitle: 'Amplify Your Impact',
        heroSubtitle: 'Draft massive grant proposals, connect with donors empathetically, and scale your outreach without hiring a copywriter.',
        icon: '❤️',
        problem: 'Non-profit directors and fundraisers are strapped for time and resources. Crafting highly emotional, persuasive grant proposals and personalized donor outreach emails requires massive cognitive and physical effort.',
        solution: 'Zavi allows you to scale your story. Speak from the heart regarding your organization\'s mission directly into your email client. Use Zavi\'s AI to polish the grammar, or use the "Casual" tone to ensure the message sounds warm and human, rather than like a corporate form letter.',
        howItWorks: [
            'Drafting a quarterly update for your top 50 donors?',
            'Dictate the raw emotional successes of the past three months into a document.',
            'Highlight the text. Tap the Magic Wand.',
            'Say: "Rewrite this as a highly persuasive, emotional email asking for end-of-year contributions."',
        ],
        benefits: [
            { title: 'Warm & Empathetic Tone', description: 'Corporate speak kills fundraising. Zavi\'s tone engine ensures your dictated outreach always feels personal, urgent, and deeply human.' },
            { title: 'Grant Proposal Magic Wand', description: 'Paste the strict formatting requirements of a federal grant. Use the Magic Wand to instantly align your raw dictation to their rigid structure.' },
            { title: 'Multilingual Outreach', description: 'Serving a diverse community? Use Live Translation to seamlessly dictate updates and WhatsApp broadcasts in Spanish, French, or Vietnamese.' },
            { title: 'Accessible & Free Tier', description: 'Zavi offers a robust Free tier for resource-strapped non-profits, providing access to our core dictation engine and intelligent grammar correction.' },
        ],
        exampleBefore: 'Voice Agent: "Find Mark Johnson on LinkedIn and send a message thanking him for his incredible generosity at the gala last night."',
        exampleAfter: '[TTS Output]: "A highly personalized LinkedIn message has been drafted and sent to Mark Johnson."',
        targetAudience: ['Non-Profit Founders', 'Fundraising Directors', 'Community Organizers', 'Social Workers'],
        faqItems: [
            { question: 'Do you offer non-profit discounts?', answer: 'Yes, please reach out to our support team with your 501(c)(3) documentation for specialized tier pricing on Zavi Pro teams.' },
            { question: 'Can it help translate our website copy?', answer: 'Absolutely. Put your cursor into your CMS, toggle the translation engine to Spanish, and dictate the English copy. Perfect translation is output instantly.' },
        ],
        relatedUseCases: ['marketers', 'email', 'translators'],
    },
    {
        slug: 'construction',
        title: 'Voice Typing for Construction & Trades',
        metaTitle: 'Voice AI for Construction — Hands-Free Field Notes | Zavi AI',
        metaDescription: 'Dictate safety reports, OSHA compliance notes, and material orders natively from the job site entirely hands-free.',
        heroTitle: 'Build Faster. Type Never.',
        heroSubtitle: 'The ultimate rugged dictation tool. Log field notes, order materials, and report safety compliance directly from the job site.',
        icon: '🏗️',
        problem: 'Project Managers, foremen, and field workers in construction wear gloves, deal with dirt, and carry heavy gear. Attempting to type out detailed Daily Logs, RFIs, or OSHA safety reports on a smartphone is nearly impossible.',
        solution: 'Zavi is built for the field. Stand in the middle of a chaotic active job site, tap the mic on your ruggedized tablet, and dictate your entire safety traverse aloud. Zavi filters the noise, formatting perfectly spelled, highly professional compliance reports instantly.',
        howItWorks: [
            'Walking the site for an end-of-day safety inspection?',
            'Open Procore or your preferred management app.',
            'Say: "The scaffolding on the east elevation needs to be secured by tomorrow morning; safety rails are slightly loose."',
            'Zavi processes the text directly into your project management software.',
        ],
        benefits: [
            { title: 'Total Hands-Free App Control (Pro)', description: 'Use the Voice Agent via your radio headset. Say: "Text the lumber supplier that we need 50 more sheets of plywood to the downtown site."' },
            { title: 'Multilingual Job Sites', description: 'The Foreman speaks English, the crew speaks Spanish. The Foreman can use Live Translation to dictate perfectly formatted Spanish texts instantly.' },
            { title: 'Extreme Acoustic VAD Filtering', description: 'Zavi\'s advanced Voice Activity Detection ensures that the sound of drills, saws, and generators won\'t trigger false text inputs.' },
            { title: 'Custom Construction Dictionary', description: 'Train Zavi to understand highly specific trade jargon: "HVAC", "Load-bearing", "Rebar", "Fascia", or specific OSHA compliance codes.' },
        ],
        exampleBefore: 'Voice Agent: "Email the architect that the plumbing rough-in failed inspection due to improper venting on the second floor."',
        exampleAfter: '[TTS Output]: "The update email regarding the plumbing rough-in inspection failure has been routed to the Architect."',
        targetAudience: ['General Contractors', 'Project Managers', 'Foremen', 'Electricians/Plumbers'],
        faqItems: [
            { question: 'Does Zavi work with Procore or PlanGrid?', answer: 'Yes. Because Zavi installs as a system-wide OS keyboard on mobile and desktop, it automatically functions flawlessly inside every construction app.' },
            { question: 'Can I use it while wearing thick gloves?', answer: 'Yes! If you map the Zavi trigger to a physical hardware button (like the iPhone Action Button) or a Bluetooth headset, you never need to touch the glass screen.' },
        ],
        relatedUseCases: ['drivers', 'hr-recruiting', 'translators'],
    }
];

export function getUseCaseBySlug(slug: string): UseCase | undefined {
    return useCases.find(uc => uc.slug === slug);
}
